### ISSUE TITLE
Discord RPC?

### ISSUE THREAD

**Issue by Zusier** [iwalton3/jellyfin-mpv-shim#100]
**Is your feature request related to a problem? Please describe.**
Could we get discord rich presence? I searched and I dont think there is any duplicates

**Describe alternatives you've considered**
i've tried MBcord and PreMid but I use mpv shim, so they wont work. 

**Additional context**
Am I the only one that would love to have this?

**Comment by iwalton3** [comment]
I have a python service lying around somewhere that did this with another project. I can look into adding it as an optional dependency/feature.

**Comment by iwalton3** [comment]
Do you have any idea what you would want the design of the rich presence integration to look like? Maybe send a screenshot or desired parameters?

This was the implementation that I did for another project, which is a music player for reference. [mrepo-discord-service.txt](https://github.com/iwalton3/jellyfin-mpv-shim/files/5066807/mrepo-discord-service.txt)

**Comment by Zusier** [comment]
Just a quick idea, could probably be better. something like this?
![Screenshot (42)](https://user-images.githubusercontent.com/46111482/90087684-e46e4780-dd0c-11ea-9c89-79c08dcdd66e.png)

**Comment by iwalton3** [comment]
So I'd probably so something like that plus I should also be able to do time remaining.

**Comment by Zusier** [comment]
yea, I was just about to send this other one
![68747470733a2f2f692e6d656d65737465722e78797a2f752f6c31642e706e67](https://user-images.githubusercontent.com/46111482/90087829-3020f100-dd0d-11ea-84ca-50dacb838c2b.png)

**Comment by iwalton3** [comment]
![image](https://user-images.githubusercontent.com/8078788/90090834-05c23a00-dcf3-11ea-9b66-bff301c94882.png)

**Comment by iwalton3** [comment]
Obviously this is disabled by default due to the privacy implications. It can be activated through the menu or the config file. (You need to quit and restart for this to take effect.)
Code is in Master, a Windows test build is here: https://iwalton.com/ushare/jellyfin-mpv-desktop_testpresence_installer.exe

**Comment by Zusier** [comment]
thats was quick! Thanks alot for this and for making the project!

**Comment by iwalton3** [comment]
Yeah it helped that I just had the code lying around. This will be in the next release, whenever that might be.

**Comment by Darkwolf1515** [comment]
Cant seem to make it work, enabled it in the player, restarted it and discord, but it wont show up on my profile.

**Comment by iwalton3** [comment]
@Darkwolf1515 If you aren't on Windows, you'll need to install extra dependencies for it to work. (I have no idea if it works in Flatpak either...) I can tell if the module is being loaded using the [log output](https://github.com/iwalton3/jellyfin-mpv-shim/wiki/Sending-Logs).

**Comment by Darkwolf1515** [comment]
I am on windows, here's your log:

{
    "always_transcode": false,
    "audio_output": "hdmi",
    "auto_play": true,
    "check_updates": true,
    "client_uuid": "cecd6daf-a080-4174-ae10-d324ecf639ec",
    "connect_retry_mins": 0,
    "desktop_fullscreen": false,
    "desktop_keep_pos": false,
    "desktop_keep_size": true,
    "desktop_scale": 1.0,
    "direct_paths": false,
    "discord_presence": true,
    "display_mirroring": false,
    "enable_desktop": false,
    "enable_gui": true,
    "enable_osc": true,
    "fullscreen": false,
    "idle_cmd": null,
    "idle_cmd_delay": 60,
    "idle_when_paused": false,
    "ignore_ssl_cert": false,
    "kb_debug": "~",
    "kb_fullscreen": "f",
    "kb_menu": "c",
    "kb_menu_down": "down",
    "kb_menu_esc": "esc",
    "kb_menu_left": "left",
    "kb_menu_ok": "enter",
    "kb_menu_right": "right",
    "kb_menu_up": "up",
    "kb_next": ">",
    "kb_pause": "space",
    "kb_prev": "<",
    "kb_stop": "q",
    "kb_unwatched": "u",
    "kb_watched": "w",
    "lang": null,
    "local_kbps": 2147483,
    "log_decisions": false,
    "media_ended_cmd": null,
    "media_key_seek": false,
    "media_keys": true,
    "menu_mouse": true,
    "mpv_ext": false,
    "mpv_ext_ipc": null,
    "mpv_ext_no_ovr": false,
    "mpv_ext_path": null,
    "mpv_ext_start": true,
    "mpv_log_level": "info",
    "notify_updates": true,
    "playback_timeout": 30,
    "player_name": "Darkwolves-pc",
    "pre_media_cmd": null,
    "remote_direct_paths": false,
    "remote_kbps": 10000,
    "sanitize_output": true,
    "screenshot_menu": true,
    "seek_down": -60,
    "seek_left": -5,
    "seek_right": 5,
    "seek_up": 60,
    "shader_pack_custom": false,
    "shader_pack_enable": true,
    "shader_pack_profile": null,
    "shader_pack_remember": true,
    "stop_cmd": null,
    "stop_idle": false,
    "subtitle_color": "#FFFFFFFF",
    "subtitle_position": "bottom",
    "subtitle_size": 100,
    "svp_enable": false,
    "svp_socket": null,
    "svp_url": "http://127.0.0.1:9901/",
    "sync_attempts": 5,
    "sync_max_delay_skip": 300,
    "sync_max_delay_speed": 50,
    "sync_method_thresh": 2000,
    "sync_osd_message": true,
    "sync_revert_seek": true,
    "sync_speed_attempts": 3,
    "sync_speed_time": 1000,
    "transcode_h265": false,
    "transcode_hi10p": true,
    "transcode_to_h265": false,
    "transcode_warning": true,
    "use_web_seek": false,
    "write_logs": true
}

**Comment by iwalton3** [comment]
That's the config file. I need the log file that would be in the same folder. It does look like it is enabled, the question is if the module is loading.

**Comment by iwalton3** [comment]
Oh also just to eliminate the possibility that multiple copies are running, kill all copies in the task manager or restart your computer.

**Comment by Darkwolf1515** [comment]
Sorry, this should be it
[log.txt](https://github.com/iwalton3/jellyfin-mpv-shim/files/5145965/log.txt)

**Comment by Darkwolf1515** [comment]
Now im getting some other weird issues (starts in a microscopic window, closes when i play music but I can still hear it), gonna just nuke it and reinstall and see if that helps

**Comment by Darkwolf1515** [comment]
Well, even after nuking it and its reg keys it still had me signed in when reinstalled, same music issue too, wonder how that works.

But ill make separate requests for those if i need to, does the rich presence rely on my server being on the internet? Mine localhost only right now.

**Comment by iwalton3** [comment]
I don't see any errors in the log, so assuming you have Discord installed and running on the computer and that you're playing something. It may take a minute or two for it to appear.

You do not need your server to be on the internet for it to work. It works by sending data to a local copy of Discord running on the same computer.

Also please note that music is currently unsupported. While it sort of works, there many other options for music playback through Jellyfin, so it is not a focus now. (The architecture was never intended for it to work well, but someone could PR in better support if they would like to.)

**Comment by Darkwolf1515** [comment]
> 
> 
> I don't see any errors in the log, so assuming you have Discord installed and running on the computer and that you're playing something. It may take a minute or two for it to appear.
> 
> You do not need your server to be on the internet for it to work. It works by sending data to a local copy of Discord running on the same computer.
> 
> Also please note that music is currently unsupported. While it sort of works, there many other options for music playback through Jellyfin, so it is not a focus now. (The architecture was never intended for it to work well, but someone could PR in better support if they would like to.)

I got that part fixed, it closed on videos, disablng display mirroring or something fixed it, music has worked great for me.

Ill wait around a bit more and see if it appears, adding the mpv shim as a game doesnt have any rpc with it so Ill just have to hope discord picks up on it
