### ISSUE TITLE
Remove language independant strings from the messages

### ISSUE THREAD

**Issue by ThibaultNocchi** [iwalton3/jellyfin-mpv-shim#101]
Hello,

I'm trying to translate some strings to french on the weblate, and encountered some strings such as this one https://github.com/iwalton3/jellyfin-mpv-shim/blob/master/jellyfin_mpv_shim/messages/base.pot#L63 where the keybindings are in the translatable string.

I think those shouldn't have to be localized, and doing so could result in ulterior problems where you want to reuse this string elsewhere or change the keybindings and you'll have to change all the translated strings.

What do you think of it?

Have a nice day.

**Comment by iwalton3** [comment]
This one I felt conflicted with. I left the [y/N] in there thinking a translation could make it clear which is which.

If you have any suggestions how to better localize this, please let me know. https://github.com/iwalton3/jellyfin-mpv-shim/blob/59526d7b2c9536a018eeec957a6fea3327b79057/jellyfin_mpv_shim/clients.py#L44

**Comment by ThibaultNocchi** [comment]
Oh yeah I didn't see this point of view. Effectively from a Linux user point of view, the y/n hint is pretty clear. But yeah I understand someone not used to it could need some help.

**Comment by iwalton3** [comment]
Looking at this though, you might be right. Unless I want to manually add all of the "yes" variants to the script, I should really remove that.
```
$ grep -R '\[.*/.*\]'
zh_Hans/LC_MESSAGES/base.po:msgid "Add another server? [y/N] "
zh_Hans/LC_MESSAGES/base.po:msgstr "添加其它服务器? [是/否] "
base.pot:msgid "Add another server? [y/N] "
fr/LC_MESSAGES/base.po:msgid "Add another server? [y/N] "
fr/LC_MESSAGES/base.po:msgstr "Ajout d'un autre serveur ? [y/N] "
nb_NO/LC_MESSAGES/base.po:msgid "Add another server? [y/N] "
nb_NO/LC_MESSAGES/base.po:msgstr "Vil du legge til en server til? [y/N] "
es/LC_MESSAGES/base.po:msgid "Add another server? [y/N] "
es/LC_MESSAGES/base.po:msgstr "¿Agregar otro servidor? [s / N] "
```

**Comment by iwalton3** [comment]
This is a fallback option for when all of the other UI options people use break anyways. I've removed the `[y/N]` prompt from all translations.
