### ISSUE TITLE
Increase server discovery timeout

### ISSUE THREAD

**Issue by LeoVerto** [iwalton3/jellyfin-mpv-shim#102]
I very much appreciate the timeout changes you made in 1.6.1, this helps immensely when connecting to remote servers!

However there is still a hardcoded 1 second timeout in the [server discovery code](https://github.com/iwalton3/jellyfin-apiclient-python/blob/996f3b0f416443fe9ef458339e7654fcffee6bdd/jellyfin_apiclient_python/connection_manager.py#L240) which prevents jellyfin-mpv-shim from adding the server even though the login was successful.

**Comment by iwalton3** [comment]
https://github.com/iwalton3/jellyfin-mpv-shim/commit/287ab33fdd8106619dd9578bcf3ae577d8aab0e6 should fix this, as the code with the one second timeout wasn't actually doing anything useful.

I'm building a Windows test build. If you are on Linux, you can test it using the [Dev instructions here](https://github.com/iwalton3/jellyfin-mpv-shim/blob/master/README.md#local-dev-installation).

**Comment by iwalton3** [comment]
https://iwalton.com/ushare/jellyfin-mpv-desktop_testauth_debug.exe

**Comment by iwalton3** [comment]
The fix for this should be in the latest release. Re-open if it is still broken.
