### ISSUE TITLE
No 32bit (Legacy) version working since v1.5.11

### ISSUE THREAD

**Issue by chp-1960** [iwalton3/jellyfin-mpv-shim#105]
**Describe the bug**
This bug happen **only for Windows 10 32bits (x86)**

If I upgrade from jellyfin-mpv-desktop_1.5.11 to any newer build (LEGACY32_installer 1.6.0 and up), the install end up fine but at the first launch I get the error "Fatal Error Detected" with the message " failed to execute script Run-Desktop". After ack of the error, the executable "run-desktop" is still in memory until I kill it with Taskman.

**To Reproduce**
1) Install "jellyfin-mpv-desktop_1.5.11**_LEGACY32_installer.exe**" on Windows 10 32bits
2) Open it to verify everything is ok
3) Upgrade to any newer version of jellyfin-mpv-desktop_**LEGACY32_installer**
4) Open it
5) ERROR : "Fatal Error Detected" with the message " failed to execute script Run-Desktop"
6) kill the MPV-desktp.exe" app from TaskMan

**Expected behavior**
After any upgrade, the application must launch and show

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 v1903 and v1909 32bits (x86). Not yet tested with v2004
 - Version : Any from 1.6.0

**Error Messages**
"Fatal Error Detected" with the message " failed to execute script Run-Desktop"

**Comment by iwalton3** [comment]
Please try this version: https://iwalton.com/ushare/jellyfin-mpv-desktop_LEGACY32_test1_installer.exe

This is technically a prerelease of the next version, but it should fix what broke in 1.6.0. I'll upload a new LEGACY32 release when the next version comes out.

**Comment by chp-1960** [comment]
😉 So quick….
Was a pleasure to help you for debugging. If you need more testings, don’t hesitate to call me.

Are able to compile the JF bbuilds from the sources ?

Cordialement,
Laurent CHIRIC.


De : Ian Walton<mailto:notifications@github.com>
Envoyé le :dimanche 16 août 2020 17:27
À : iwalton3/jellyfin-mpv-shim<mailto:jellyfin-mpv-shim@noreply.github.com>
Cc : chp-1960<mailto:chp_1960@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [iwalton3/jellyfin-mpv-shim] No 32bit (Legacy) version working since v1.5.11 (#105)


Closed #105<https://github.com/iwalton3/jellyfin-mpv-shim/issues/105>.
