### ISSUE TITLE
Client needs to be resized again to show properly

### ISSUE THREAD

**Issue by harry71019** [iwalton3/jellyfin-mpv-shim#106]
**Describe the bug**
Desktop client shows the contents out of place. Re-fullscreen the client solves the problem

**To Reproduce**
1. Open desktop client
2. See that content is placed out of place.

**Expected behavior**
Shows content in place at startup

**Screenshots**
Here's a video that shows the bug
https://youtu.be/UjzmIWbs8ZE

**Desktop (please complete the following information):**
 - Windows
 - 1.7.1
 - Monitor is a secondary monitor 27" 1080p 100% scaling in Windows

**Comment by iwalton3** [comment]
I’ve already substantially changed how sizing of the window works for the next release. I’ll make a debug build and you can test that one.

**Comment by harry71019** [comment]
Nice to hear that, looking forward to test it. Thanks!

**Comment by iwalton3** [comment]
https://iwalton.com/ushare/jellyfin-mpv-desktop_sizing1_installer.exe

**Comment by harry71019** [comment]
I just tested the new client and it does solve the problem. Quick question, the previous web client remembers where I last opened it, and it always opens on the second monitor, but now it doesn't. Is this intentional or was the previous behavior just a coincident and not a function? Thanks!

**Comment by iwalton3** [comment]
Yes that was intentional. You can re-enable it, but with it will likely come the resizing issue.

A large number of users were having issues with it not showing up at all at times, so I changed the default to only remember the size.

**Comment by harry71019** [comment]
I understand now, thanks for the explanation!

**Comment by iwalton3** [comment]
Changes have been released.
