### ISSUE TITLE
Ability to set jellyfin-mpv-shim as the default player in the web client

### ISSUE THREAD

**Issue by TonCherAmi** [iwalton3/jellyfin-mpv-shim#112]
**Is your feature request related to a problem? Please describe.**
The core functionality works flawlessly, thanks a lot. However it is extremely annoying that I need to manually select jellyfin-mpv-shim in the cast menu on every single page refresh.

**Describe the solution you'd like**
A config option that would allow me to set jellyfin-mpv-shim as the default player in the web client.

**Comment by iwalton3** [comment]
This would probably be a request against https://github.com/jellyfin/jellyfin-web. The trick is where to store the preference.

I do have something like this implemented in the desktop fork of the web client, although it uses out-of-band communications with the web client to do it and is not configurable.

**Comment by TonCherAmi** [comment]
@iwalton3 I figured as much, that's unfortunate. To be honest it irks me so much I'm willing to do pretty much anything to get this to work, could you point me in the direction of where you have that implemented? I'm looking at `webclient_view/__init__.py` and can't quite figure it out.

**Comment by iwalton3** [comment]
Just remember that this was written as a patch and not intended to be PR’d back. It’s very much the wrong way to go about it.

https://github.com/iwalton3/jellyfin-web/blob/master/src/bundle.js#L194

**Comment by iwalton3** [comment]
The web client is being rewritten, so I’m not too invested in these patches. A better integration in the future will likely be done.

**Comment by TonCherAmi** [comment]
Understood, I really appreciate it, thanks!

**Comment by TonCherAmi** [comment]
In case anyone else is as desperate as me, this tampermonkey script seems to work:

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://jellyfin:8096/*
// @grant        none
// ==/UserScript==

(function() {
  'use strict';

  window.setTimeout(() => {
    window.require(["playbackManager"], ({ default: playbackManager }) => {
      playbackManager.getTargets().then(targets => {
        const target = targets.find(target => target.deviceName === 'YOUR player_name GOES HERE')

        if (target) {
          playbackManager.trySetActivePlayer(target.playerName, target)
        }
      })
    })
  }, 1500)
})();
```
