### ISSUE TITLE
Screenshots can't be saved

### ISSUE THREAD

**Issue by ayyu** [iwalton3/jellyfin-mpv-shim#119]
**Describe the bug**

**To Reproduce**
1. Play any video through the MPV Shim using the Cast to button in Jellyfin
2. Attempt to take a screenshot using either the s key or c > Take Screenshot

**Expected behavior**
Screenshot should be saved on the desktop. When I use another copy of MPV and open a local video file, taking a screenshot with the s key works.
I have tried turning hardware acceleration on and off, it doesn't work in either case.

**Screenshots**
![image](https://user-images.githubusercontent.com/11494813/93845778-1eb5f780-fc70-11ea-98c1-95dabf117923.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.8.0

**Error Messages**
2020-09-22 01:02:23,768 [   ERROR] mpv: cplayer: Error opening 'mpv-shot0003.jpg' for writing!
2020-09-22 01:02:23,768 [   ERROR] mpv: cplayer: Error writing screenshot!

**Comment by iwalton3** [comment]
It must be trying to write it somewhere where it doesn't have rights. Try changing the "start in" for the shortcut to the desktop.

**Comment by ayyu** [comment]
Thank you, that solved it. Changed it to this:

![image](https://user-images.githubusercontent.com/11494813/93846122-2c1fb180-fc71-11ea-87b0-e5485160ae5e.png)

**Comment by iwalton3** [comment]
I know on Linux it goes in my home folder by default, so I should probably just change the shortcut location. I wonder if MPV has a screenshot folder parameter.

**Comment by ayyu** [comment]
There is a screenshot-directory setting, under the [pseudo-GUI section](https://mpv.io/manual/master/#pseudo-gui-mode)

**Comment by iwalton3** [comment]
So I'll add a conf.json setting for that. Defaulted to the desktop on Windows, unset on other platforms.

**Comment by iwalton3** [comment]
This has been implemented and tested on Windows.

If you would like to try the fix, you can [download the installer here](https://artprodcus3.artifacts.visualstudio.com/Af8b3f627-969b-4284-9f33-c9b0fdbdc993/aab8f3fe-76b5-40d1-97ad-2e95e0148cf2/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2l3YWx0b24zL3Byb2plY3RJZC9hYWI4ZjNmZS03NmI1LTQwZDEtOTdhZC0yZTk1ZTAxNDhjZjIvYnVpbGRJZC82MC9hcnRpZmFjdE5hbWUvRGVza3RvcEluc3RhbGxlcg2/content?format=file&subPath=%2Fjellyfin-mpv-desktop_1.8.0_installer.exe).
