### ISSUE TITLE
[Question] Using MPV Scripts with flatpack

### ISSUE THREAD

**Issue by dgalli1** [iwalton3/jellyfin-mpv-shim#123]
Hi i got some struggle with integrating a custom mpv lua script into your flatpack package.
It doesn't load no matter what i try
I belive i have to set the path in the mpv.conf file right?
So this is what i tried so far in the mpv.conf file:
scripts=./scripts/force_resolution.lua -> i thought flatpack might make the paths wierd so i tried it relative
scripts=/home/damian/.config/mpv/scripts/
scripts=/home/damian/.config/mpv/scripts/force_resolution.lua

I read somewhere on reddit that you're using scripts yourself so i thought you might be able to help me out.

**Comment by iwalton3** [comment]
You must specify the entire, absolute path to the script in the mpv configuration. This is made harder by the fact that Flatpak mangles the path to the configuration file. When you first run the application from the command line, it will print the absolute path to the configuration directory.

**Comment by dgalli1** [comment]
Thank you this seems to work.
But it seems like i have to ditch flatpack anyways, because i was trying to call xrandr to set my screen resolution. And this obviously doesn't work in the sandbox of flatpack.
Thank you anways.
