### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by bobhope9848** [iwalton3/jellyfin-mpv-shim#124]
Describe the bug:
Scrolling in JellyFin desktop causes subprocess.exe to spike at 50% cpu usage. Application also lags while this is happening.

To Reproduce
1. Wait about 10-15 minutes with the program open sitting idle.
2. Try scrolling down and watch subprocess.exe usage on task manager.

Expected behavior
Should be a consistent 3-8% usage on subprocess.exe

Screenshots
[Snip of TaskMgr.exe](https://i.imgur.com/9ZMiqvq.png)

Desktop
 - OS: Windows 10 2016 LTSB
 - Version 1.80

Error Messages
Log:
[jellyfin_log.txt](https://github.com/iwalton3/jellyfin-mpv-shim/files/5287608/jellyfin_log.txt)

**Comment by iwalton3** [comment]
This is because the webview is slow. Short term the solution is to cast to the shim mode. Long term I plan to switch to QT for the UI and you’ll be able to auto-cast from your web browser to make using it with the web app easier.

**Comment by bobhope9848** [comment]
> This is because the webview is slow. Short term the solution is to cast to the shim mode. Long term I plan to switch to QT for the UI and you’ll be able to auto-cast from your web browser to make using it with the web app easier.

Ah I see, I'll close then. Thanks for messaging so quick.
