### ISSUE TITLE
Default seek times should be set according to the skip(Forward/Back)Length Jellyfin settings

### ISSUE THREAD

**Issue by mijofa** [iwalton3/jellyfin-mpv-shim#13]
**Is your feature request related to a problem? Please describe.**
I was a little torn whether this should be a bug or a feature request. Not really a bug but the current behaviour of the left/right seeking is surprising.

**Describe the solution you'd like**
In the jellyfin web UI there's an option for each of Skip forward length and Skip back length under the playback options, which changes how far the fast-foward/rewind buttons go forward/back when viewing media in the web browser.
I believe setting these should affect how far back/forward pressing the left/right arrow keys seek in mpv.

This setting comes from the json at /DisplayPreferences/usersettings under CustomPrefs.skipForwardLength and CustomPrefs.skipBackLength

**Describe alternatives you've considered**
The seek distance should at least be configurable (perhaps in conf.json or mpv.conf) I'm not too fussed where, that just seemed like the best spot that's already there for you

**Additional context**
I tried to write this code myself but I hit a roadblock when I couldn't find any reference to the usersettings endpoint in jellyfin-apiclient-python so I think some updates to that apiclient are required first.

**Comment by iwalton3** [comment]
Yes an extension to the API client is needed to do this. It should be straightforward to implement though.

The default bindings for MPV of precise seek using left and right and coarse seek using up and down is actually one of my favorite features of the MPV keybinds and one I think a lot of people are used to.

I think the way I’ll handle this is I’ll use the Jellyfin configuration for the media keys. The web remote control already seeks by whatever the default is. Then I’ll add a config/menu setting to change the arrow behavior if desired.

**Comment by iwalton3** [comment]
This has been implemented and will be in the next release.

**Comment by mijofa** [comment]
I wasn't finding the ffwd/rew buttons on the Android client last night, but I've noticed now that they only appear when the device is in landscape mode. So I didn't realise they actually still worked as I'd expect them too, less bugged by this surprising behaviour now that I'm aware of that. Happy to just close this task with that in mind.

I'll probably see about messing with the CSS a bit to get those buttons appearing in portrait mode as well, but that has nothing to do with this repo.
