### ISSUE TITLE
Problem playing media at one server in question. 

### ISSUE THREAD

**Issue by kokomo123** [iwalton3/jellyfin-mpv-shim#130]
**Describe the bug**
The bug happens when i'm trying to connect via websockets to play a movie. MPV Shim doesn't pop up, nor mpv desktop gives any warning. 

Attention! Please be sure to avoid posting any API keys. I don't want other people to be able to compromise your server!
API Keys are now removed from logs by default, but they may still appear in other places, such as on MPV info screens.

**To Reproduce**
1. Connect to friends server
2. Play any media
3. Nothing happens. Nothing pops up

**Expected behavior**
I was trying to play a movie and nothing pops up. MPV Shim seems to crash, nothing else. 

**Screenshots**
N/A. 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 10 2004 Build 19041.572
 - Version [e.g. 1.2.0]: 1.8.0

**Error Messages**
Please provide logs, as they are often needed for me to understand and quickly troubleshoot the issue. You can read instructions for how to do so here:
https://github.com/iwalton3/jellyfin-mpv-shim/wiki/Sending-Logs
[log.zip](https://github.com/iwalton3/jellyfin-mpv-shim/files/5447595/log.zip)

**Comment by iwalton3** [comment]
The websocket endpoint on the server is returning a 404 error. The most likely cause is incorrect configuration of the reverse proxy. Please have the server admin reconfigure their server to forward the websocket, per this article: https://jellyfin.org/docs/general/networking/nginx.html

**Comment by kokomo123** [comment]
Well, he will dig into it. I'll close this PR and reopen if necessary.
