### ISSUE TITLE
Discord Rich Presence: change "Playing ..." message

### ISSUE THREAD

**Issue by Neolel** [iwalton3/jellyfin-mpv-shim#131]
![Preview](https://i.imgur.com/lssps60.png)

Would it be possible to change the "Jellyfin MPV shim" part of this message with the name of the media you are watching? The above screenshot should say something like "Playing Game of Thrones" instead.

**Comment by iwalton3** [comment]
From what I can tell, Discord does not allow this. The name is something I set in the Discord Developer Portal.
