### ISSUE TITLE
MPV Shim's player backend is not connected error

### ISSUE THREAD

**Issue by rajlego** [iwalton3/jellyfin-mpv-shim#135]
**Describe the bug**
When trying to play anything:
Playback Error
MPV Shim's player backend is not connected. This could be caused by many things. Try logging out/in again and making sure websockets work.

**To Reproduce**
1. login to jellyfin
2. try to play something
3. error as show in screenshots

**Expected behavior**
When I try to play something, it plays.

**Screenshots**
![image](https://user-images.githubusercontent.com/5921902/99864948-60114780-2bcc-11eb-86a2-e8c42e81dd77.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 LTSC
 - Version 17763

**Error Messages**
Logs:
[mpv-shim-log.txt](https://github.com/iwalton3/jellyfin-mpv-shim/files/5576861/mpv-shim-log.txt)

**Comment by iwalton3** [comment]
```
2020-11-21 11:05:01,239 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: Websocket url: wss://jellyfin.kcalvinalvin.info//socket?api_key=REDACTEDREDACTED&device_id=e6b1bd43-7898-4e31-8d55-d64d8755a0c0
2020-11-21 11:05:01,241 [   DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): jellyfin.kcalvinalvin.info:443
2020-11-21 11:05:01,460 [   ERROR] JELLYFIN.jellyfin_apiclient_python.ws_client: Handshake status 404 Not Found
2020-11-21 11:05:01,460 [   DEBUG] event_handler: Unhandled Event WebSocketError: Handshake status 404 Not Found
2020-11-21 11:05:01,461 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: ---<[ websocket ]
2020-11-21 11:05:01,461 [    INFO] clients: No connection to server. Next try in 1 second(s)
```

You are getting a 404 error with the websocket. You need to make sure your reverse proxy is configured correctly for MPV Shim to work.

**Comment by lurui45** [comment]
> ```
> 2020-11-21 11:05:01,239 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: Websocket url: wss://jellyfin.kcalvinalvin.info//socket?api_key=REDACTEDREDACTED&device_id=e6b1bd43-7898-4e31-8d55-d64d8755a0c0
> 2020-11-21 11:05:01,241 [   DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): jellyfin.kcalvinalvin.info:443
> 2020-11-21 11:05:01,460 [   ERROR] JELLYFIN.jellyfin_apiclient_python.ws_client: Handshake status 404 Not Found
> 2020-11-21 11:05:01,460 [   DEBUG] event_handler: Unhandled Event WebSocketError: Handshake status 404 Not Found
> 2020-11-21 11:05:01,461 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: ---<[ websocket ]
> 2020-11-21 11:05:01,461 [    INFO] clients: No connection to server. Next try in 1 second(s)
> ```
> 
> You are getting a 404 error with the websocket. You need to make sure your reverse proxy is configured correctly for MPV Shim to work.

Could you specify how to have correct configuration? I have a same problem, but my media server is emby installed on nas at my home, and i connected it remotely by DDNS in another place, the connection is good, because I could see my movies and eposides, just cannot play it, warnning"MPV Shim's player backend is not connected error"

**Comment by iwalton3** [comment]
> my media server is emby installed on nas at my home

Sorry, but only JellyFin is supported. Not Emby.

**Comment by lurui45** [comment]
> > my media server is emby installed on nas at my home
> 
> Sorry, but only Jellyfin is supported. Not Emby.

ok..., do you have plan to support emby in future?

**Comment by iwalton3** [comment]
I do not. Emby is closed source, so working on it is difficult as I have to reverse engineer it. Jellyfin and Emby have diverged too much for it to be practical too, as the desktop mode uses the Jellyfin web client.
