### ISSUE TITLE
mpv-shim broken with latest MPV

### ISSUE THREAD

**Issue by jrch2k20** [iwalton3/jellyfin-mpv-shim#137]
**LOG**
2020-12-02 18:47:12,519 [    INFO] conf: Loaded settings from json: /home/junior/.config/jellyfin-mpv-shim/conf.json
Traceback (most recent call last):
  File "/usr/bin/jellyfin-mpv-shim", line 33, in <module>
    sys.exit(load_entry_point('jellyfin-mpv-shim==1.8.0', 'console_scripts', 'jellyfin-mpv-shim')())
  File "/usr/lib/python3.9/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 64, in main
    from .player import playerManager
  File "/usr/lib/python3.9/site-packages/jellyfin_mpv_shim/player.py", line 36, in <module>
    import mpv
  File "/usr/lib/python3.9/site-packages/mpv.py", line 514, in <module>
    backend.mpv_client_api_version.restype = c_ulong
  File "/usr/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libmpv.so.1: undefined symbol: mpv_client_api_version

**MPV version**
[cplayer] Command line options: '-v'
[cplayer] mpv 0.33.0-1-gfa7afc3e19 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Nov 22 18:50:57 -04 2020
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.51.100
[cplayer]    libavcodec      58.91.100
[cplayer]    libavformat     58.45.100
[cplayer]    libswscale      5.7.100
[cplayer]    libavfilter     7.85.100
[cplayer]    libswresample   3.7.100
[cplayer] FFmpeg version: n4.3.1
[cplayer] 
[cplayer] Configuration: ./waf configure --prefix=/usr --confdir=/etc/mpv --enable-libmpv-shared --enable-dvdnav --enable-cdda --enable-libarchive --lua=luajit
[cplayer] List of enabled features: alsa asm build-date caca cdda cplayer cplugins cuda-hwaccel cuda-interop debug-build drm dvdnav egl egl-drm egl-helpers egl-x11 ffmpeg ffnvcodec gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo librt linux-fstatfs linux-input-event-codes lua luajit memfd_create optimize plain-gl posix posix-or-mingw pthreads pulse rubberband shaderc shaderc-shared stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vapoursynth vdpau vt.h vulkan wayland wayland-protocols x11 xv zimg zlib

Tyvm for your time

**Comment by iwalton3** [comment]
This looks like a problem in python-mpv. https://github.com/jaseg/python-mpv

You can try using the external mpv mode to circumvent this issue.

**Comment by jrch2k20** [comment]
Tyvm for your time and sry i didn't notice python MPV was a thing, i'll make the report there.
