### ISSUE TITLE
Not sending Discord rich presence when not watching content

### ISSUE THREAD

**Issue by FrouxBY** [iwalton3/jellyfin-mpv-shim#142]
Hi, 
Thanks for this great work, everything work as expected on my side !

I was trying the Discord Rich Presence Integration, and I tought I would prefer if it dit only send presence when I am actually watching something, and not when I just have the Jellyfin-MPV-shim app open, 
I don't know if its doable easily, but if maybe this could be an other options  (like Full, only while watching, None) if other people like to have it always on ?

Thanks anyway, this is not a priority for sure

**Comment by iwalton3** [comment]
It should only be sent while you are watching something.

**Comment by FrouxBY** [comment]
I just tried, and my friend has confirmed that they see "Playing Jellyfin" when the app is open

**Comment by iwalton3** [comment]
Did you add it as a game or enable the rich presence option in the menu? It should say “Playing Jellyfin MPV Shim”.

**Comment by FrouxBY** [comment]
Allright thanks, 

The first time I tried it was not working when playing a video, so I add it manually as a game, but obviously it means displaying it every time.
Now I have removed the hardcoded entry, and it works just fine as expected when playing a video, 

Thanks for your help !

**Comment by iwalton3** [comment]
That is likely because you have to restart the client for it to load the rich presence.
