### ISSUE TITLE
Try to reconnect to the server after a failed initial connection

### ISSUE THREAD

**Issue by Neolel** [iwalton3/jellyfin-mpv-shim#144]
**Is your feature request related to a problem? Please describe.**
Every now and then, Jellyfin MPV Shim fails to connect to my server on startup which runs on the same machine. I guess something happens that dealys the server's start causing Jellyfin MPV shim to not be able to find the server on the initial check. 

**Describe the solution you'd like**
Let Jellyfin MPV shim to check for the server again automatically every X seconds with X increasing after every unsuccessful connection. This would solve the problem of having to close it and reopen it again. 

**Describe alternatives you've considered**
automatically closing the old instance of Jellyfin MPV Shim when you open it anew, would be a nice little feature as well. As far as I can understand, there is no reason to have two instances of it running anyways.

**Additional context**
The alternative option is only relevant (at least for me) since the newest version which caused Jellyfin MPV Shim to not open in the tray anymore but only have two running processes which I need to manually close through the task manager on Windows. I don't know if this is a new feature but even if not, it wouldn't be a problem if the aforementioned problems didn't exist.

**Comment by iwalton3** [comment]
> since the newest version which caused Jellyfin MPV Shim to not open in the tray anymore

Re-download the latest release. I messed up the release and fixed the download.

As for handling connection failures on startup, the `connect_retry_mins` is what you want.
