### ISSUE TITLE
Cannot use external player (mpc-qt)

### ISSUE THREAD

**Issue by ComteNiark** [iwalton3/jellyfin-mpv-shim#151]
Hello! In the process of switching from Plex to Jellyfin, I've been trying to configure this client. Everything works fine on the jellyfin side, but as a MPC-HC user, I don't really like the default MPV look. I see that the client has an option for using an external MPV installation, and it just so happens one suits my needs (mpc-qt). However, when I try to point the config towards the .exe, the client keeps launching videos using the built-in default MPV.

Here are my relevant config lines:
`  "mpv_ext": true,
    "mpv_ext_ipc": null,
    "mpv_ext_no_ovr": false,
    "mpv_ext_path": D:\\Program Files\\QT\\mpv.exe,
    "mpv_ext_start": true,`

Any help would be greatly appreciated.

**Comment by iwalton3** [comment]
You need to put quotes around the file path. Other steps may be needed depending on the software characteristics.

**Comment by ComteNiark** [comment]
Oh, I feel very dumb now. I'll try it. Thanks.
