### ISSUE TITLE
Can I decide the subtitle style by editing the configuration?

### ISSUE THREAD

**Issue by vflanker** [iwalton3/jellyfin-mpv-shim#159]
**About**
There is no doubt that jellyfin-mpv-shim/desktop is really an awesome application. Recently I am wondering if the style of subtitle can be changed? Now I can only see the **position**, **size** and **color** but I want to change the line-out color(by default is black). Is this been written in the application? The bare black line-out is a little cheap when comparing to Jellyfin Web Player or PotPlayer(In fact I like the PotPlayer's style, it appears to be a trans background and the subtitle has no line-out).

**Desire**
Make jellyfin-mpv better!

**Comment by iwalton3** [comment]
You can use the MPV configuration to apply a custom subtitle stylesheet.

**Comment by dkourem** [comment]
My congrats on your excellent work! I use windows binary release v1.8.1of the jellyfin-mpv-shim/desktop. Please can you provide any useful guide in order to apply a custom suttitle stylesheet in windows binary release?

**Comment by vflanker** [comment]
> My congrats on your excellent work! I use windows binary release v1.8.1of the jellyfin-mpv-shim/desktop. Please can you provide any useful guide in order to apply a custom suttitle stylesheet in windows binary release?

maybe can take potplayer as an example :)

**Comment by dkourem** [comment]
> > My congrats on your excellent work! I use windows binary release v1.8.1of the jellyfin-mpv-shim/desktop. Please can you provide any useful guide in order to apply a custom suttitle stylesheet in windows binary release?
> 
> maybe can take potplayer as an example :)

the potplayer is alone a great subtitle project! It has so many features! But I like MPV player, it's simple and plays well. I ask just if it possible to do some bit changes as changing the colour of the font. I can't find the MPV conf file. Thanks.

**Comment by dkourem** [comment]
SOLVED: just open "Jellyfin MPV Shim" -> "Application menu" -> (full screen black screen mode) but working -> Video preference -> list of subtitles properties - Colour and Done!

**Comment by iwalton3** [comment]
Looks like this is good to close. Glad to hear that worked.
