### ISSUE TITLE
Make this compatible with emby

### ISSUE THREAD

**Issue by popeye2468** [iwalton3/jellyfin-mpv-shim#164]
Ok so i use both emby and jellyfin and i really like this desktop app much more that emby theatre, 

so can you make this compatible with Emby? i can log in and see all libraries and it will play movies, thre issue is when it comes to TV shows i can browse main covers etc but when click on it, it stays forever loading and not loading seasons and episodes etc

so please and pretty please could you make it compatible?

Thanks

**Comment by iwalton3** [comment]
Emby is unsupported. The UI is provided by the Jellyfin project and has diverged from Emby to the point of incompatibility.
