### ISSUE TITLE
Bug: Unable to remap Up and Down Arrow Keys

### ISSUE THREAD

**Issue by Eisa01** [iwalton3/jellyfin-mpv-shim#167]
**Describe the bug**
In order to change the event of Up and Down keys,
inside `config.json` I have changed the values of  `seek_up` and `seek_down` to `null`

Also, I added the following inside `input.conf`
```
UP    add volume 2
DOWN  add volume -2
```

Normally adding this will change up and down arrow keys to increase and decrease the volume in mpv. 

**To Reproduce**
1. Simply try to override the arrow up and down keys to any other event inside `input.conf`, and it will not work.

**Expected behavior**
mpv player should replace the up and down arrow keys without problems using `input.conf`, and I should be able to use them for changing volume level instead of seeking.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 20H2

**Comment by iwalton3** [comment]
This is a duplicate: https://github.com/iwalton3/jellyfin-mpv-shim/issues/120
