### ISSUE TITLE
How can I close the pywebview window?

### ISSUE THREAD

**Issue by busywhistling** [iwalton3/jellyfin-mpv-shim#169]
Is there a way to exit from the application without manually killing the command in terminal? Perhaps an option to click on?

**Comment by iwalton3** [comment]
Is this in full-screen mode? Alt-F4 works on Windows. Whatever your platform's close shortcut is should as well.

**Comment by busywhistling** [comment]
Ah right, thanks. I was using [sway](https://github.com/swaywm/sway) on linux, and my shortcut `$mod+Shift+q` works.
