### ISSUE TITLE
Not Starting on Ubuntu

### ISSUE THREAD

**Issue by WisdomCode** [iwalton3/jellyfin-mpv-shim#17]
**Describe the bug**
After following the steps in the README, the app does not start succesfully on Linux. The mpv was not recompiled as I have used mpv for a while on my device and it always delivered. Don't have any weird data formats in jellyfin either.
I removed my config of mpv for testing purposes (~/.config/mpv) as well

**To Reproduce**
1. Install jellyfin-mpv-shim according to the README.md on Xubuntu 18.04 LTS x64
2. Start it by typing jellyfin-mpv-shim into the console as there is no startmenu link

**Expected behavior**
Something should start, preferrably a window

**Desktop (please complete the following information):**
 - OS: Xubuntu 18.04 LTS 64 Bit

**Error Messages**
```
2020-02-14 15:24:51,516 [    INFO] Loaded settings from json: /home/drone/.config/jellyfin-mpv-shim/conf.json

(jellyfin-mpv-shim:29313): dbind-WARNING **: 15:24:51.615: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jellyfin_mpv_shim/mpv_shim.py", line 32, in main
    from .player import playerManager
  File "/usr/local/lib/python3.6/dist-packages/jellyfin_mpv_shim/player.py", line 520, in <module>
    playerManager = PlayerManager()
  File "/usr/local/lib/python3.6/dist-packages/jellyfin_mpv_shim/player.py", line 69, in __init__
    input_media_keys=True, include=mpv_config, **extra_options)
  File "/usr/local/lib/python3.6/dist-packages/python_mpv_jsonipc.py", line 272, in __init__
    for command in self.command("get_property", "command-list"):
  File "/usr/local/lib/python3.6/dist-packages/python_mpv_jsonipc.py", line 375, in command
    print(self.mpv_inter.command(command, *args))
  File "/usr/local/lib/python3.6/dist-packages/python_mpv_jsonipc.py", line 223, in command
    raise MPVError(data["error"])

```

Also, I've had it run in a python console in verbose, and it gave me this additional line
`python_mpv_jsonipc.MPVError: property not found
`

And lastly it should be noted that the program does not actually crash but runs indefinetly without any output or reaction until you CTRL+C it. Taskmanager says it takes about 60 MB Ram but no 0% CPU.

**Comment by iwalton3** [comment]
There are two solutions:
 - Install the libmpv1 package for ubuntu. (sudo apt install libmpv1)
 - Alternatively, If you recompile MPV from source this will fix the problem.

The issue is that the version of MPV that Ubuntu is providing is missing the command list property, which is currently required for the IPC-based backend to work.

I’ll also look into making the IPC backend work with that ubuntu version.

**Comment by iwalton3** [comment]
The underlying issue has been fixed. You should be able to use the software without applying any of those alternatives I mentioned. All you need to do is upgrade your copy of python-mpv-jsonipc:
```
sudo pip3 install --upgrade python-mpv-jsonipc
```

**Comment by WisdomCode** [comment]
Nice, that was quick! Thanks, its working!
