### ISSUE TITLE
Can start, and stream to device, but no gui/player appears

### ISSUE THREAD

**Issue by monik3r** [iwalton3/jellyfin-mpv-shim#26]
On clear linux I've followed installation instructions, installing via pip3. I can seemingly start jellyfin-mpv-shim, however when I stream to the linux system no window/video/player appears. 

One interesting debug WARNING message was:
```[ WARNING] This mpv version doesn't support on-screen controller.```

Otherwise, I'm not quite sure what this should look like while using it. It seems like the videos are being played back somewhat from the mobile android app, and the player is using CPU on the clear linux system. Some videos while casted get up to 6 seconds then go back to 0:00 (however other than cpu usage I'm not seeing any player or like actual media). 

Is there any way to know what jellyfin-mpv-shim should look like when functioning properly? I didn't see screenshots anywhere. Thanks!

**Comment by iwalton3** [comment]
It should look like this after you cast something: https://jellyfin.org/images/mpv-shim/blender.png

It sounds like your MPV may not be working. I would suggest building MPV from source. If you don't already see a message like `Staring MPV from mpv.`, then you are using `libmpv1` MPV support and you may be able to get the program working by editing the config file (`~/.config/jellyfin-mpv-shim/conf.json`) and changing `mpv_ext` to `true`.

If you want to see the errors from MPV, you can run MPV separately and connect to it. Change these config options:
```
"mpv_ext": true,
"mpv_ext_path": null,
"mpv_ext_ipc": "/tmp/mpv-socket",
"mpv_ext_start": false,
```
Then launch mpv with `mpv -v --input-ipc-server=/tmp/mpv-socket --idle` and launch the shim. Any errors from MPV should show in the console where you started it.

**Comment by monik3r** [comment]
Thanks for the help with debugging. I believe I have a bad build of ffmpeg (not supporting aac audio or h264).
