### ISSUE TITLE
[mac] Stopping playback won't return to Display Mirroring

### ISSUE THREAD

**Issue by philosen** [iwalton3/jellyfin-mpv-shim#28]
**Describe the bug**
Display mirroring is shown in fullscreen (shown in the dock as Python). After starting playback it changes to mpv. Stopping playback won't return to the display mirroring screen, but to desktop.

I assume this has to do with the mac version using an external version of mpv. Will there be a full application at some point?

**To Reproduce**
1. Run jellyfin-mpv-shim
2. Start playback
3. Stop playback
4. Not returning to display mirroring

**Expected behavior**
After stopping playback display mirroring should be the front window

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.4

**Comment by iwalton3** [comment]
Platforms behave differently with full screen. On Windows I have a platform-specific extension that hides and re-displays display mirroring. Linux doesn’t appear to need it.

Unfortunately I can’t develop the platform-specific extension to get mirroring to behave on OSX, so I’m marking this as “needs help”.

(The external player behaves the same as the libmpv one, the difference is only in the way the API works, not the appearance and general behavior.)

**Comment by philosen** [comment]
Ok, got it. I think the problem is the way macOS is handling fullscreen. Each applications that is activating fullscreen will open as a new "desktop space" and when leaving full screen it's going back to the desktop where the application was originally started. I hope that makes sense..

**Comment by iwalton3** [comment]
It might be possible to add an `media_ended_cmd` and `stop_cmd` in the config that returns to the workspace with the mirroring open in it. This is a workaround and is not really ideal though.

**Comment by iwalton3** [comment]
This might be resolved. You can test it by installing from the git master:
```
git clone https://github.com/iwalton3/jellyfin-mpv-shim
git submodule update --init
pip3 install --upgrade .
```
(Please note that the new desktop client will *not* work when installed like that. You'd have to clone it and pull a copy of the webclient per the Windows instructions.)

**Comment by iwalton3** [comment]
The changes that could have fixed this were released a while back. If this is still an issue, please re-open. (I cannot test this myself.)
