### ISSUE TITLE
Using IINA with shim

### ISSUE THREAD

**Issue by theg00s3** [iwalton3/jellyfin-mpv-shim#29]
**Is your feature request related to a problem? Please describe.**
I'm trying to get [IINA](https://iina.io/) to work with shim but I can't seem to get it to work.

**Describe the solution you'd like**
A way to configure shim to use IINA instead of the default mpv client

**Additional context**
IINA is an mpv-based video player written in Swift.
IINA does have an mpv.conf file that can be used

**Comment by theg00s3** [comment]
Just using the command line, typing "/Applications/IINA.app/Contents/MacOS/iina-cli *file*" opens IINA and frees up the terminal, while typing "/Applications/IINA.app/Contents/MacOS/IINA *file*" opens IINA, but the terminal window can't be closed without closing IINA as well.

**Comment by iwalton3** [comment]
So what you’d have to do is configure IINA’s MPV to listen on a socket. If you can configure an MPV config, use input-pic-server=/tmp/mpvsocket. If you can configure a custom command argument, use --input-pic-server=/tmp/mpvsocket. If you can’t do either, you might have to modify and recompile the player.

Please note that it may be impossible to integrate the player nicely. For instance, gnome-mpv worked but smplayer later did not when I tested. It mostly depends on how much the application will tolerate external control of MPV. You may also need to configure idle=yes or --idle.

**Comment by theg00s3** [comment]
I think IINA is like smplayer in the fact that it does not cooperate nicely with shim.

I can get it to work if I use the console in shim to get the url for the content (https://DOMAIN/Videos/4e2170027aa921e45998c534a41de9ad/stream?static=true&MediaSourceId=4e2170027aa921e45998c534a41de9ad&api_key=[key]) and then input that into IINA, but that's a very long winded way of doing it

**Comment by iwalton3** [comment]
I would look to see if there is another MPV GUI you like or see if IINA can be patched. Unfortunately there really isn’t anything I can do.

**Comment by theg00s3** [comment]
I've made a issue over at [IINA's GitHub repo](https://github.com/iina/iina/issues/2809) to see if someone over there can help patch/fix it

**Comment by burgerga** [comment]
(Just to let you that we managed to get it to work with IINA in the issue linked above :))
