### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by theg00s3** [iwalton3/jellyfin-mpv-shim#3]
Despite my credentials being correct, jellyfin-mpv-shim can't authenticate itself.

Here are the command prompt readouts: https://pastebin.com/g4QKuNci

**Comment by iwalton3** [comment]
If possible, could you provide the corresponding logs from the server? It just says in that log that the login was unauthorized.

**Comment by iwalton3** [comment]
I've re-written a lot of the authentication logic for the newest release. Could you check to see if you are still having problems?

**Comment by theg00s3** [comment]
It works now, thanks
