### ISSUE TITLE
Subtitles don't work

### ISSUE THREAD

**Issue by dessalines** [iwalton3/jellyfin-mpv-shim#30]
I've tried many films, selecting the subtitles from jellyfin:

![image](https://user-images.githubusercontent.com/930215/76890597-0b0f7b80-685e-11ea-988b-e0274f15f522.png)

But they don't show up in mpv: 

![image](https://user-images.githubusercontent.com/930215/76890674-28dce080-685e-11ea-8db2-53e323226d9c.png)

The default behavior should probably be just to send all the subtitles along into mpv anyway, selecting the one selected from that menu if possible.

Note: I can't use the toolbar menu because I use i3. I don't know what configuring the shim would need to do from this menu, but it should probably have a web interface so its usable across all DE's and OS's.

**Comment by iwalton3** [comment]
Are you using external subtitles? Currently you can only select non-default external subtitles either from Jellyfin remote control or via the built-in menu. (Press "c" while MPV is open and use the arrow keys, enter, and esc to navigate the menus. You can set subtitles as default for a TV season if they aren't already selected by default using that menu as well.)

If you cannot see the subtitles listed in the menu, please send me the logs with the config `log_decisions` as `true`. Note that the current version of Jellyfin also apparently has [some issues with subtitles](https://github.com/jellyfin/jellyfin/issues/2525).

> The default behavior should probably be just to send all the subtitles along into mpv anyway, selecting the one selected from that menu if possible.

There is no nice way to do that for external subtitles without forcing the player to download all of the external subtitles before the video can play. Hence why the built-in menu exists.

> I can't use the toolbar menu because I use i3.

I use i3 and the systray menu works fine. See [this page for documentation on enabling systray in i3](https://i3wm.org/docs/userguide.html#_tray_output). You can also use the command-line mode for mpv shim. (This can be enabled in the [config file](https://github.com/iwalton3/jellyfin-mpv-shim#configuration).) Regardless, the menu is accessible from within mpv using the "c" keybind.

**Comment by dessalines** [comment]
Ah thanks! Didn't know about the `c` keybind. 

 tried several movies, and although that menu shows the correct subtitles, selecting them did nothing. 

I'm on the newest versions of jellyfin and mpv. 

I'll try to turn on the logging later on and report back.
```
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.2
```

**Comment by iwalton3** [comment]
Does Jellyfin 10.5.2 fix this issue? https://github.com/jellyfin/jellyfin/releases/tag/v10.5.2

**Comment by dessalines** [comment]
Arch repos are a little slow to update this one, I'll report back soon.

**Comment by dessalines** [comment]
Yup works now, thanks!
