### ISSUE TITLE
OSD menu ignoring and resetting font-size options in mpv.conf

### ISSUE THREAD

**Issue by whtv** [iwalton3/jellyfin-mpv-shim#31]
**Describe the bug**
Opening the menu (shortcut "c") will reset osd-font-size (and possibly other options) set in mpv.conf until a restart of jellyfin-mpv-shim.

**To Reproduce**
1. Set "osd-font-size" in mpv.conf (e.g =25)
2. Cast a video to jellyfin-mpv-shim and open the menu

**Expected behavior**
The menu should use osd-font-size from mpv.conf

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by iwalton3** [comment]
I have resolved this issue. You can install from the git master for the time being, it may be a little while until I release a new version.

```bash
sudo pip3 install --upgrade git+https://github.com/iwalton3/jellyfin-mpv-shim
```

**Comment by whtv** [comment]
Thanks!
