### ISSUE TITLE
Music playback always starts at track #1

### ISSUE THREAD

**Issue by joytrekker** [iwalton3/jellyfin-mpv-shim#34]
Using version 1.4.2 on windows
If I open a music album and try to cast any track only track #1 will play. The expected behavior is for example clicking on track 5 and track 5 plays. I think the entire album is getting queued since I can press play next to play track 2, 3, 4 etc... The same issue occurs with music playlists.

**Comment by iwalton3** [comment]
There is a lot of work needed to get music playback working ideally. (It isn't listed as an actual feature yet.) There are other options in the mean time though, such as [mopidy plugin](https://github.com/jellyfin/mopidy-jellyfin), [jellycli](https://github.com/tryffel/jellycli), and [jfmp](https://github.com/n-peugnet/jfmp).

**Comment by iwalton3** [comment]
The fix is now released: https://github.com/iwalton3/jellyfin-mpv-shim/releases/tag/v1.5.8

**Comment by gerroon** [comment]
Maybe this is the same bug but the playback does not follow what is in the client app. it seems like the client app (android or android web app) always seems to be one or two songs behind. If this is a separate issue i can open a new bug. I was not sure.

**Comment by iwalton3** [comment]
Maybe there are unhandled playback commands or they aren’t being handled properly.

The caveat with bad music support in this app still stands, but feel free to open another issue. Please provide detailed logs and reproduction instructions, ideally with the web client.
