### ISSUE TITLE
[Feature Request] Make Jellyfin MPV Desktop remember its last window position, state and size

### ISSUE THREAD

**Issue by whalehub** [iwalton3/jellyfin-mpv-shim#35]
**Is your feature request related to a problem? Please describe.**
At the moment, Jellyfin MPV Desktop always starts as a small, about 800x600 large window in the center of the screen. It does this even if you launch it again after having changed its window position, state (e.g. maximized) and/or size during the previous run. Many applications on Windows memorize these parameters when you quit them and recreate them on the next launch.

**Describe the solution you'd like**
Ideally, Jellyfin MPV Desktop would store these options in a file whenever it is shut down and apply them at the next start by reading them from said file.

**Describe alternatives you've considered**
There are applications like Sizer for quickly resizing another application to a specific size.

**Additional context**
N/A

**Comment by iwalton3** [comment]
It looks like this is a possibility, as the library does support it. https://pywebview.flowrl.com/guide/api.html

**Comment by iwalton3** [comment]
This has been implemented in version 1.5.3.

**Comment by whalehub** [comment]
@iwalton3 Thanks!
