### ISSUE TITLE
Possible Bug? Does not save movie position nor resume from position

### ISSUE THREAD

**Issue by leaderdog** [iwalton3/jellyfin-mpv-shim#36]
I've just been fooling around with Jellyfin until there is a suitable windows 10 desktop replacement for Plex to use on my htpc.

I like what you've done here, but I've got a question about the save position.

I had a movie that I had previously started watching in kodi to test and I chose it to run in your software, but it started from the beginning, It didn't give an option to resume.

When I quit watching a show, it didn't save the location.

I don't know if this is something you have implemented or if I did something wrong.  I tried a few times all with the same results.

**To Reproduce**

1. run a movie - either one with a previous resume location or not
2. Movie starts from the beginning.
3. close movie (either with C - menu only shows close mark watched or unwatched depending on movie state, or U just kills it.
4. start up movie again, it starts from the beginning.

**Expected behavior**
Seeing as it's a server I'm hoping the behavior would be similar to Jellyfin's, or that of plex to keep track of what I've seen or in progress shows.

**Desktop (please complete the following information):**
 - Windows 10 (1909)
 - Version 1.5.4 (only version I've tried)

As a side question.  Can I use Flirc with my harmony remote to program movement on the page?  It seemed arrows wouldn't move around the main page to make selections.  If that's not in yet, no worries, just curious. :)

**Comment by iwalton3** [comment]
Press q to close and save progress. The menu option and u/w specifically don’t save progress within the video.

You should be able to set the web client to TV mode which allows control with arrow keys.

**Comment by leaderdog** [comment]
Oh excellent, that worked.  I might need to try this out on my htpc.

Thanks!
