### ISSUE TITLE
Transcoding entire episode on updating position

### ISSUE THREAD

**Issue by aclogar** [iwalton3/jellyfin-mpv-shim#38]
**Describe the bug**
When resuming an episode or movie It appears to try and transcode the entire episode up to that point before playing.  When resuming a show it will show the loading screen while ffmpeg is using all the available cpu to transcode.  Similar is happening when trying to seek forward and backwards within a video.

The time to resume increases the farther into a video you seek to.  i.e resuming a video that is only a few minutes into it would under a minute to begin, but if you seek to an hour into a movie it takes over 15 minutes.

This issue happens even if the media item is direct playing.

**To Reproduce**
1. Go to any video half watched
2. Click on play
3. See buffer

**Expected behavior**
What is expected to happen in when resuming or seeking it should skip to designated position and buffer from there.

**Screenshots**
https://imgur.com/a/jMo6Xg9

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.5.4

**Error Messages**
Please provide the console output by clicking the systray icon and selecting "Show Console".

**Comment by iwalton3** [comment]
Your client is broken. Videos are loading in the webview and not MPV.

Please try the following: 

 - Run `rd /s /q %appdata%\jellyfin-mpv-shim\cache` in a command prompt window.
 - Log out from the web client and log in again.

The upper right corner should show as if you're connected to a device. When playing video, it should play fullscreen in a dedicated MPV window.

**Comment by iwalton3** [comment]
This issue is stale and is the result of a broken configuration, not a software defect.

Please comment if you would like help resolving this.
