### ISSUE TITLE
Export client as a jellyfin-apiclient-python module

### ISSUE THREAD

**Issue by n-peugnet** [iwalton3/jellyfin-mpv-shim#4]
Hi ! I'm interested in building a minimalist music player for jellyfin and I thought that python would be great for the job.
I saw that you already implemented an apiclient for python so I was wondering if you would be ok to export it as an external python module ?

**Comment by iwalton3** [comment]
I've extracted the API client to the pip package `jellyfin-apiclient-python`. Please note that the API client is not complete. I've had to add features to it while writing this project. If you'd like to add a feature, please send a pull request. The source repository is here: https://github.com/iwalton3/jellyfin-apiclient-python

**Comment by n-peugnet** [comment]
Thank you that was fast !

I didn't see that you used the apiclient from Jellyfin Kodi. Wouldn't it be better if both of your projects used the same library ? Maybe we should ask them to work on it together ?

**Comment by iwalton3** [comment]
Yeah, the fact that I had to fork the API client isn't really ideal. I'm not sure what the package management situation for Kodi looks like, so maybe there was a reason why it was bundled? The changes aren't too significant though, so it should be possible to have them both use the same library if `six` is added as a dependency again.
