### ISSUE TITLE
Freeze when Resizing window

### ISSUE THREAD

**Issue by limon** [iwalton3/jellyfin-mpv-shim#40]
1.5.4 + Windows 10
Sometimes when I resize the window the program freezes and no responding, I have to terminate it. Resizing slightly is generally OK, but if drag large and small too much it occurs.

**Comment by iwalton3** [comment]
This is a known problem with the upstream CEF renderer. https://github.com/r0x0r/pywebview/issues/484

The other renderer that I could use with pywebview is Microsoft Edge which crashes more often for me when testing.

I will watch the pywebview project to see when this is released and update accordingly.

**Comment by iwalton3** [comment]
https://github.com/r0x0r/pywebview/releases/tag/3.3

**Comment by limon** [comment]
Great, thank you!

**Comment by iwalton3** [comment]
This will be integrated in the next packaged release. (The windows version bundles the dependencies and likely needs some other tweaks to work with this.)

**Comment by iwalton3** [comment]
This appears to be resolved in the current master. Fixed will be in next release.

**Comment by iwalton3** [comment]
This is now in 1.5.11.
