### ISSUE TITLE
Windows 10 32 bits

### ISSUE THREAD

**Issue by angeltonio** [iwalton3/jellyfin-mpv-shim#41]
the program does not run on this architecture

**Comment by angeltonio** [comment]
First of all thanks for your work, it is amazing, what happens is that I have an old laptop that I cannot put windows 64 bits so I would have liked a 32 bit version. It would also have been great to have some portable version, without the need for installers ... greetings and thanks again.

**Comment by iwalton3** [comment]
> It would also have been great to have some portable version, without the need for installers ...

I used to have a portable release for the main application (the installer was recently made), but the client libraries would get marked as blocked by the system and cause all sorts of errors. The installer avoids this and doesn't need admin rights.

The regular shim application (that doesn't bundle 300 MB worth of dependencies to show the web client within the program) is portable. You can connect to it through your web browser instead. (It still isn't 32 bit though.)

**Comment by iwalton3** [comment]
I've made build scripts for 32 bit. Unfortunately, it looks like the 32 bit version of PyInstaller is used by malware developers, so you're antivirus (in my case Windows Defender) may freak out.

You can download the builds here: https://mega.nz/folder/XIFXnSIR#V-l-gKRYNyaPbjBJ_MYe9w

Due to the false positive issue I don't really want to post these in the regular release section.

**Comment by angeltonio** [comment]
Hello, the 32-bit version did not work, it tells me that the mpv-1.dll file cannot be loaded, it is not made to work in windows, I do not understand that. regards

**Comment by angeltonio** [comment]
Can help me with this..please...

**Comment by iwalton3** [comment]
That mpv was the i686 build from the mpv site. Let me know if you can run this: https://sourceforge.net/projects/mpv-player-windows/files/32bit/

You’ll need 7zip to extract the download.

**Comment by iwalton3** [comment]
I would like to add that if that mpv version doesn't work but you can find one that does, then you can likely configure that as an external mpv with the existing 32 bit installer.

**Comment by angeltonio** [comment]
Hello, download the latest version of mpv that you gave me in the link and if it opens correctly ... something else I need to do ... greetings and thanks for answering ..

**Comment by iwalton3** [comment]
Yeah configure it as external mpv. Go to `%appdata%` in Explorer, click on `jellyfin-mpv-shim` and open `conf.json` in a text editor.
Change `mpv_ext` from `false` to `true`.
Change `mpv_ext_path` from `null` to `"C:\\path\\to\\mpv.exe"`.
Then hopefully you'll be able to run it.

**Comment by angeltonio** [comment]
Hello where is the conf.json, because in that folder it´s not, it´s possible to recompile a 32 bits with that version on mpv that you shared on the link??..because it´s work...greetings...

**Comment by iwalton3** [comment]
Pyinstaller ignored the directive to use the 32 bit version of MPV and instead packaged the 64 bit version...
Please try this version: https://iwalton.com/ushare/jellyfin-mpv-desktop_1.5.5_LEGACY32_installer.exe

**Comment by angeltonio** [comment]
It worked !!! .. thanks for everything, I have not fully tested it yet, but I will tell you how it works, although I saw a bit of slowness when loading the videos ... regards

**Comment by iwalton3** [comment]
I wish you the best of luck.

> although I saw a bit of slowness when loading the videos

Well it does sound like a pretty old computer. If the videos don't open full-screen in a different window though then that is a problem.

**Comment by angeltonio** [comment]
Yes, I think that's it, I only have 2 gigs of ramm and the microprocessor is not good ..., have you thought about adding support for touchscreens?

**Comment by iwalton3** [comment]
> about adding support for touchscreens

For the new desktop client, that just embeds the web app which isn't super friendly to touch screens. I'm not sure how touch-aware Windows 10 is if you put it in touch screen mode or if the webview even supports things like touch scrolling. The actual MPV interface is highly keyboard driven and not something I can easily change. (The entire UI for that part is from MPV and cannot really be changed by me.)

**Comment by iwalton3** [comment]
Closing as the 32 bit build works.

**Comment by Longshot** [comment]
> Pyinstaller ignored the directive to use the 32 bit version of MPV and instead packaged the 64 bit version...
> Please try this version: https://iwalton.com/ushare/jellyfin-mpv-desktop_1.5.5_LEGACY32_installer.exe

Could you reupload the legacy version please.
My crappy 32bit uefi atom laptop can't run the 64 bit version.

**Comment by iwalton3** [comment]
Here is an updated build: https://iwalton.com/ushare/jellyfin-mpv-desktop_1.5.10_LEGACY32_installer.exe

**Comment by angeltonio** [comment]
Thanks a lot...I going to test it more, but on my tablet pc with Windows 10 32 bits work fine...cheers and thanks...Are you think you can put it on releases too??..
