### ISSUE TITLE
Cannot launch on MacOS

### ISSUE THREAD

**Issue by lkopiec** [iwalton3/jellyfin-mpv-shim#43]
Hi, so i did every step on the install readme on macos, but when im trying to run it im getting this:
`zsh: command not found: jellyfin-mpv-shim`

Also when im trying to install desktop or gui version im getting:
`zsh: no matches found: jellyfin-mpv-shim[desktop]`
`zsh: no matches found: jellyfin-mpv-shim[gui]`

**Comment by iwalton3** [comment]
It sounds like your python scripts folder isn’t in the PATH.

Please see here for how someone on OSX solved the issue: https://github.com/tdryer/hangups/issues/222

**Comment by lkopiec** [comment]
Thanks, that fixed the cli version, but im still getting those:
`zsh: no matches found: jellyfin-mpv-shim[desktop]`
`zsh: no matches found: jellyfin-mpv-shim[gui]`
when trying to install

**Comment by iwalton3** [comment]
The desktop version is called `jellyfin-mpv-desktop`.

**Comment by iwalton3** [comment]
However, the desktop version is currently broken on OSX. I will probably have that fixed shortly. You can monitor that here: https://github.com/iwalton3/jellyfin-mpv-shim/issues/42

**Comment by iwalton3** [comment]
Closing as the "command not found" issue was solved. Please monitor and report on fixing the desktop client in issue #42.
