### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by Alice-Schuberg** [iwalton3/jellyfin-mpv-shim#44]
I simply installed and ran as 'jellyfin-mpv-desktop_1.5.4_installer.exe'
But no window pops up
ReedMe stated that the jellyfin webui is floating, but it is not visible.
[https://imgur.com/GD9Vhxd](https://imgur.com/GD9Vhxd)
Am I not understanding this program?

I am using Windows 10 1909

**Comment by iwalton3** [comment]
So when you run the `run-desktop.exe` nothing happens?

Try the debug build here:  https://mega.nz/#!2Vc3gIRJ!yHg_RA6UgTKrBYlfL8W9i50CP13JwU_JFDYxE1SrQDo

Right click on the zip when you finish downloading it, select Properties, and uncheck "Block". Then extract it and run the run-desktop.exe. If you get an error `System.IO.FileLoadException` then that means the libraries didn't get unblocked before you unzipped them. Please provide the error output from the console window. If your server is publicly available, make sure to remove any API keys if there are any listed.

If a console window pops up and immediately disappears, run the run-desktop.exe instead by dragging it into a "Command Prompt" window and pressing enter.

**Comment by Alice-Schuberg** [comment]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 0: invalid start byte

I checked the above error

Windows language is Korean.
Folder path used only in English

**Comment by iwalton3** [comment]
There should be more of an error along with the message. Could you provide the entire error message?

**Comment by Alice-Schuberg** [comment]
2020-04-04 00:58:49,840 [    INFO] conf: Loaded settings from json: C:\Users\@@@\AppData\Roaming\jellyfin-mpv-shim\conf.json
2020-04-04 00:58:50,157 [    INFO] player: Using libmpv1 playback backend.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "jellyfin_mpv_shim\webclient_view\__init__.py", line 93, in run
  File "site-packages\werkzeug\serving.py", line 848, in make_server
  File "site-packages\werkzeug\serving.py", line 740, in __init__
  File "socketserver.py", line 452, in __init__
  File "http\server.py", line 139, in server_bind
  File "socket.py", line 676, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 0: invalid start byte

**Comment by iwalton3** [comment]
It looks like you're computer's name contains characters which are not valid UTF-8. If you rename your computer to something that doesn't contain non-ascii characters it should work.

This is a bug in Python itself: https://bugs.python.org/issue9377

**Comment by Alice-Schuberg** [comment]
I solved all the problems and this works
