### ISSUE TITLE
Multiple JMS on the same pc

### ISSUE THREAD

**Issue by gerroon** [iwalton3/jellyfin-mpv-shim#45]
Since there is no QA section I am posting this under here.

**Describe the solution you'd like**
It would be nice if one can run multipl versions of this app on the same pc. The reason is that, one could cast certain content to one another content to another one. For instance one cancast movies to one and tutorials to another one with 1.5x MPV  speed. It looks like JMS remembers the last speed in the last casting, this gets a bit confusing, like one watches a tutorial at 1.5x speed then casting a movie means that the movie will play at 1.5x too. Sure the solution is to reach to the keyboard and mess with the speed settings, however this is not always an optimum solution. Given that a keyboard is not always ready or the remote pc is somewhere else etc.

**Describe alternatives you've considered**
Not sure if there is analternative.

**Additional context**
Multiple JMS on the same pc with speed playing memory.

**Comment by iwalton3** [comment]
> It looks like JMS remembers the last speed in the last casting

Yeah the same instance of MPV is used across playbacks, so any native MPV playback options you change through MPV will stay in effect until you restart the application.

Right now the MPV Shim cannot run multiple copies because all instances would share the same client ID and authorization. I can add a command-line argument to allow you to use a different config folder. (You could then set the speed for each player in `mpv.conf` so it persists across restarts as well.) Would this help?

**Comment by gerroon** [comment]
Hi

That sounds like it would be worth try.

**Comment by iwalton3** [comment]
You can now run the program with a custom config option by specifying `--config CONFIG` on the command to launch the player. You cannot run a second copy of the desktop client though, only the shim. (This is because the desktop client starts an internal web server that isn't currently on a configurable port.)

To test the changes in the two issues:
```
git clone https://github.com/iwalton3/jellyfin-mpv-shim
cd jellyfin-mpv-shim
git submodule update --init
wget https://github.com/iwalton3/jellyfin-web/releases/download/jwc1.5.2-3/dist.zip
unzip dist.zip
rm dist.zip
mv dist/ jellyfin_mpv_shim/webclient_view/webclient
sudo pip3 install --upgrade .
```

**Comment by gerroon** [comment]
Hi

Thanks for the update. Where do I put the speed stuff?

**Comment by gerroon** [comment]
Also trying to run the new version in (/opt/jellyfin-mpv-shim2)

` python3 jellyfin_mpv_shim/mpv_shim.py --config /home/USER/.config/jellyfin-mpv-shim2/conf.json `

```
Traceback (most recent call last):
  File "mpv_shim.py", line 11, in <module>
    from . import conffile
ImportError: attempted relative import with no known parent package
```

**Comment by iwalton3** [comment]
In the config folder you specify, edit `mpv.conf` and add `speed=1.5`.

You need to run the command `jellyfin-mpv-shim` or `run.py` with the arguments. Running `jellyfin_mpv_shim/mpv_shim.py` doesn't work due to issues with relative imports.

**Comment by gerroon** [comment]
Ok

I was able to run but hitting an issue here. So I can run the both versions but Jellyfin Web client only shows the last connected client in the list, even when both versions are running. I changed the client name in the conf.json already.

**Comment by iwalton3** [comment]
Did you change the uuid and sign in again on the new one?

**Comment by gerroon** [comment]
Well it created a new conf, so it seems to havea  new uuid. I assume I need to readd the accounts.

**Comment by iwalton3** [comment]
Yes you need to re-add the account on the newly configured player. I can confirm it works if you specify a blank directory, let it create a new config, and log in:
![image](https://user-images.githubusercontent.com/8078788/78463867-1eb93f80-76b0-11ea-90a2-7aaed9fe0f64.png)

**Comment by gerroon** [comment]
Thanks for your help, I ws trying to avoid adding all those creds again.

I  think this should work. Feel free to close this.

**Comment by gerroon** [comment]
@iwalton3 

I did an update the other day, and it seems like both versions I set up either using the same config path or not respecting the config set in the command line, because both MPVs start at 1.0 speed and when I right click to open the config path both of them opens `/home/USER/.config/jellyfin-mpv-shim`

Maybe this feature is not in the current master?

**Comment by iwalton3** [comment]
It looks like it still works for me. You launched it like this?
```
jellyfin-mpv-shim --config ~/Desktop/jf-conf-test
```
Notably running it with `--config=~/Desktop/jf-conf-test` will not work.

**Comment by gerroon** [comment]
Does it open the correct config folder when you ricgkth click on the tray icon?

**Comment by iwalton3** [comment]
No, that is fixed in the latest commit now.
