### ISSUE TITLE
publish jellyfin-mpv-desktop on flathub

### ISSUE THREAD

**Issue by krodelabestiole** [iwalton3/jellyfin-mpv-shim#47]
Hello, I think it would be nice to distribute the app as a Flatpak. It would be very easy to install to anyone using any Linux distro (+ there is no usual issue with GTK or Qt themes since we don't see it at all).

I've never done that before but I managed to write a manifest that works. Here it is : [com.github.iwalton3.jellyfin-mpv-desktop.txt](https://github.com/iwalton3/jellyfin-mpv-shim/files/4435400/com.github.iwalton3.jellyfin-mpv-desktop.txt)
(It's a json but github only accept txt extensions.)
Lines 0 to 181 have been widely copied from the [Celuloid](https://github.com/flathub/io.github.celluloid_player.Celluloid) manifest (which is a gui for MPV) and I'm not sure every modules are required. Then I'm pretty confident lines 182 to the end are clean, they have been generated with [Flatpak PIP Generator](https://github.com/flatpak/flatpak-builder-tools/tree/master/pip) from the pip `jellyfin-mpv-shim[desktop]` package.

You can try it with :
```
flatpak install flathub org.gnome.Sdk//3.36
flatpak install flathub org.gnome.Platform//3.36
mv com.github.iwalton3.jellyfin-mpv-desktop.txt com.github.iwalton3.jellyfin-mpv-desktop.json
mkdir build
flatpak-builder build com.github.iwalton3.jellyfin-mpv-desktop.json --force-clean
flatpak-builder --run build com.github.iwalton3.jellyfin-mpv-desktop.json jellyfin-mpv-desktop
```

I guess the last things to do would be to create a desktop launcher and [submit it to Flathub](https://github.com/flathub/flathub/wiki/App-Submission) but if you agree I think this role is devolved to the author @iwalton3 more than I.

There might also be little adjustements, e.g. I have not worked on systray features.

**Comment by iwalton3** [comment]
Thanks for the manifest. I was looking into AppImage as an easier install option, but it looked really involved. I'll look into what is required to get this set up.

**Comment by cromefire** [comment]
snaps are also a nice thing that are separated quite nicely and feature (actually working) auto updates: https://snapcraft.io/

**Comment by krodelabestiole** [comment]
A few years ago you had to choose between deb and rpm, now you have to choose between deb, rpm, flatpak, snap and appimage... big improvement ^^

I'm (half) kidding, any of appimage, snap or flatpak would do great since they run on any linux distro.
I've just went with flatpak because of flathub, the security of its use and ease of upgradability (compared to appimage), and because I don't like the way canonical is forcing the use of snaps in its distro and always tries to push its own tech instead of contributing to the existing.
But deep down I'm agnostic on this so I don't really care... the best would of course to have it distributed everywhere but that's a lot of unnecessary work.

@iwalton3 sorry I'm not fluent with english and I wonder what you mean by "AppImage looks really involved" ?

**Comment by cromefire** [comment]
It's complicated too implement

**Comment by iwalton3** [comment]
After working on this a bit, it looks like getting the whole application packaged in flatpak is going to be a mess. This is mostly because the gui mode has a dependency on Tkinter and that isn't provided by the base runtime. Compiling Python from source has proven ineffective because the pystray icon doesn't work with the source-based version.

I can provide a degraded version of the application (with only the desktop client and the cli shim version), but that is less ideal.

**Comment by krodelabestiole** [comment]
what's the use of the systray icon ? I don't have it on windows and I don't feel like missing any functionality....

**Comment by iwalton3** [comment]
> what's the use of the systray icon ? I don't have it on windows and I don't feel like missing any functionality....

There are three primary operational modes of the player:
 - Desktop Player - The program starts a webview containing the web client and allows you to play directly.
 - GUI Mode - You start the application in the background, and then you can cast to it like a Chromecast. There is a systray icon and GUI to manage connections and logs, but you're not constantly running a web browser to be able to cast media. 
 - CLI Mode - When all else fails, everything is managed on the command line. This makes it a pain to manage the servers.

**Comment by krodelabestiole** [comment]
ok, then I understand the use for the GUI / shim mode (casting).

But I think the vast majority of desktop Linux users are still looking for a reliable, user friendly simple Jellyfin client for their devices. That could read most of the format without server re-encoding (not as web browsers).
(And other than kodi which is a pain to setup and has the worst ergonomy on a desktop.)
... and simple to install.

From this standpoint I think a jellyfin-mpv-desktop flatpak, snap or appimage with or without systray icon would just do great !

**Comment by iwalton3** [comment]
I'm actually getting pretty close to having a release out. I have a working flatpak manifest and I'm currently preparing to publish 1.5.6 to get that fully up to date.

**Comment by iwalton3** [comment]
The application is now on flathub! https://flathub.org/apps/details/com.github.iwalton3.jellyfin-mpv-shim
