### ISSUE TITLE
Custom keybinds for volume?

### ISSUE THREAD

**Issue by calmcacil** [iwalton3/jellyfin-mpv-shim#48]
**Is your feature request related to a problem? Please describe.**
Ability to control volume using mouse wheel.

**Describe the solution you'd like**
It'd be nice if it was solved with a simple config variable, or simply respecting input.conf, i tried it but it seemed to be "stuck" on seek.

**Describe alternatives you've considered**
Tried to add multiple keybinds for volume control to input.conf in both %appdata%/mpv and %appdata%\jellyfin-mpv-shim but it didnt seem to make much of a difference.

**Comment by iwalton3** [comment]
I added the ability to configure input in the master branch, which will be in the next version.

For now you can put this into `mpv.conf`:
```
input-conf=~/.config/jellyfin-mpv-shim/input.conf
```

**Comment by calmcacil** [comment]
Thanks, greatly appreciate the quick fix.
