### ISSUE TITLE
[Feature Request] Add an option to specify the install path in the Jellyfin MPV Desktop installer

### ISSUE THREAD

**Issue by whalehub** [iwalton3/jellyfin-mpv-shim#49]
**Is your feature request related to a problem? Please describe.**
If a software is installed outside of the Program Files directory, its files are left unprotected from malicious changes by other applications that are running without admin rights.

**Describe the solution you'd like**
I would prefer it if the installer allowed people to specify where they want to install Jellyfin MPV Desktop and prompt the user for admin rights if required.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by iwalton3** [comment]
It looks like the only way to support this is either to [bundle abandoned plugins](https://nsis.sourceforge.io/UAC_plug-in) into the NSIS installer or package two installers. I might have to look for something nicer than NSIS to implement this.

I looked at Python's installer for instance, but it looks like they built it from scratch.

**Comment by whalehub** [comment]
@iwalton3 I looked through my collection of installers for FOSS and found one software whose installer handles this quite nicely. I recorded a couple of .gifs to showcase its installer.

**Installing Session Desktop in `C:\Program Files\Session`** - admin prompt pops up

![2020-04-08_03-08-58](https://user-images.githubusercontent.com/44198148/78734070-8d63fa80-7947-11ea-9b47-de9da585dfce.gif)

**Installing Session Desktop in `C:\Users\Aaron\AppData\Local\Programs\Session`** - no admin prompt

![2020-04-08_03-10-14](https://user-images.githubusercontent.com/44198148/78734091-98b72600-7947-11ea-96ad-e9d9e8b92eb8.gif)

The source code for this software can be found here: <https://github.com/loki-project/session-desktop>

**Comment by iwalton3** [comment]
I investigated and they are using electron-builder, which produces an NSIS installer. Unfortunately there is no way I can use electron-builder directly with this project. There is nothing simple or easy about trying to re-purpose the NSIS code either. https://github.com/electron-userland/electron-builder/tree/master/packages/app-builder-lib/templates/nsis

I might look into other install frameworks, but the easiest option is just to distribute two installers.

**Comment by iwalton3** [comment]
Update: Inno Setup 6 supports it. (https://github.com/jrsoftware/issrc)

**Comment by whalehub** [comment]
@iwalton3 Good find! Inno Setup seems to be a very commonly used installer software as well.

**Comment by iwalton3** [comment]
I have updated the installer in the releases page. Inno Setup is *so* much nicer to set up and use than NSIS. I should have used that one from the start.

**Comment by whalehub** [comment]
@iwalton3 Thank you! The new installer works really well.
