### ISSUE TITLE
Unable to quit when playing ts files muxed in a mkv container

### ISSUE THREAD

**Issue by harry71019** [iwalton3/jellyfin-mpv-shim#5]
So currently there's a show that I have which were originally .ts files and I simply remuxed them into a mkv file. When playing these files, playing, seeking all these functions work as intended.  However, when you try to exit the player (either by pressing q or closing the window) the window freezes and I have to close and restart the shim program.

 Also, the statistics such as current play file/codec etc will be wrong and will be from the file previously played. For example, here's me playing the aforementioned .ts file. (this is a japanese drama so clearly not les miserables)
![image](https://user-images.githubusercontent.com/59645782/72590840-b3d84380-38cc-11ea-8ef7-5817c7a6fb0e.png)

I believe the file being originally .ts is a possible cause seeing that this is my only show which was previouly this kind of file type. Here's the media info from mpc-hc:
[逃げるは恥だが役に立つ 第01話「プロの独身男と秘密の契約結婚」1080p BDRip x265 FLAC-Japari Park.mkv.MediaInfo.txt](https://github.com/iwalton3/jellyfin-mpv-shim/files/4075431/01.1080p.BDRip.x265.FLAC-Japari.Park.mkv.MediaInfo.txt)

**Comment by iwalton3** [comment]
Were there any errors in the console when you tried to quit from the program? Also are you using Windows or Linux?

**Comment by harry71019** [comment]
I'm running windows 10. Also, I need to correct myself. Trying to close the window or quit from the player doesn't do anything. The video just keeps on playing (seeking still available) and when it finishes, the screen turns black.(but you could still rewind and play the video). The only way to shut it down would be to close the app or start playing something else.
When I start running the video, here's the error log from the console

> 2020-01-17 02:24:17,029 [   ERROR] error from callback <function WSClient.run.<locals>.<lambda> at 0x000001F5065EE8B8>: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by iwalton3** [comment]
That error message means there is something that is undefined when I don't expect it to be. I'll try reproducing this locally tomorrow. I may also post a test version.

**Comment by iwalton3** [comment]
I have a test build that should (theoretically) solve both of the issues you've posted. Could you test it? https://iwalton.com/ushare/jellyfin-mpv-shim_test2.exe

**Comment by harry71019** [comment]
Yes now it solves both issues. Thank you very much!
