### ISSUE TITLE
[Feature Request] Add optional update check on startup

### ISSUE THREAD

**Issue by whalehub** [iwalton3/jellyfin-mpv-shim#50]
**Is your feature request related to a problem? Please describe.**
I personally have a GitHub account, so I can just watch the releases on this repository to be notified when an update is released, but my friends and family don't, so it would be nice for them to have a way to be notified about new releases.

**Describe the solution you'd like**
I'm not sure what the best way to implement this on a technical side would be, but it could be added as an option in the installer that is unchecked by default, something like "Check for new Jellyfin MPV Desktop updates on startup."

**Describe alternatives you've considered**
My friends and family could sign up for a GitHub account and watch the releases on this repository as well.

**Additional context**
N/A

**Comment by nwithan8** [comment]
Of course it's you asking for this, Aaron :)
I'd like to help if I can. I'll fork the repo and take a look.
Maybe lift some code from ginstall?

**Comment by iwalton3** [comment]
My thoughts were to just query GitHub to see if there is a new version. The trick is notifying the user, since there are four separate user interfaces for the program.

The easy way out would be to just show and OSD message on MPV the first time something is played.

**Comment by iwalton3** [comment]
Looks like this would be an easy way to do it. It wouldn't be hitting something I host, so there is less of a privacy concern.
```
curl --head https://github.com/iwalton3/jellyfin-mpv-shim/releases/latest
HTTP/1.1 302 Found
(... snip ...)
location: https://github.com/iwalton3/jellyfin-mpv-shim/releases/tag/v1.7.0
```

**Comment by iwalton3** [comment]
The next version will have update checks. These work by querying GitHub for a redirect to the latest release. If it doesn't match the current version, it will:
 - Notify the user via a message in MPV the first time they play something.
 - Add a menu option to open the new release in the browser.

Naturally notifications and update checking can be disabled in the config file. I have enabled it by default.
