### ISSUE TITLE
Icons not displayed correctly in desktop view

### ISSUE THREAD

**Issue by atm0915** [iwalton3/jellyfin-mpv-shim#52]
**Describe the bug**
In the desktop view, icons are not displayed correctly as shown below.

**To Reproduce**
1. Go to any page
2. See that icons are not displayed correctly.

**Expected behavior**
The correct icons should show instead of text or broken icons

**Screenshots**
jellyfin-mpv-desktop:
![image](https://user-images.githubusercontent.com/4145112/79029861-edcb8580-7b5b-11ea-809c-6e5c2408eb76.png)
Jellyfin Web Interface:
![image](https://user-images.githubusercontent.com/4145112/79029892-09cf2700-7b5c-11ea-86f3-c6f693cd9fa5.png)

**Desktop:**
 - OS: Arch Linux
 - Version 1.5.5

**Comment by iwalton3** [comment]
This seems to be working on both Debian Stable and the Flatpak Runtime version. I wonder if there is something wrong with font rendering on your current version of WebKitGTK, which is used by pywebview.

A quick work-around to this issue would be to install from Flatpak.

**Comment by atm0915** [comment]
Using Flatpak did seem to fix it, although that is not ideal for me. Obviously this is not related to jellyfin-mpv-shim itself, so feel free to close it if you wish, but I couldn't find any other reports of this problem with WebKitGTK or pywebview, so do you have any ideas on how I could further debug this issue?

**Comment by iwalton3** [comment]
I'm not sure. My next step would be to get devtools in the webview.

The easiest way would be to edit line 211 in `/usr/local/lib/python3.7/dist-packages/jellyfin_mpv_shim/webclient_view/__init__.py` (or the comparable folder on Arch Linux) to have `debug=True` in it. That allows [access to the devtools](https://pywebview.flowrl.com/guide/debugging.html).

**Comment by atm0915** [comment]
Unfortunately I couldn't get the debug=True to work. I've been trying for a fair bit now and I can't get any semblance of a right click menu to show up and allow me to inspect and get to the dev tools. None of the common shortcuts for dev tools seemed to open them up either. I guess I will close this issue and see if I can figure this out.
