### ISSUE TITLE
Playlist plays from the first file regardless of selection

### ISSUE THREAD

**Issue by Cupbox** [iwalton3/jellyfin-mpv-shim#53]
Possibly related to #34 
When I try to play a video from a playlist, playback always starts from the first file.

**To Reproduce**
- Create a playlist of videos.
- Try to play a video other than the first.
- First video plays

**Expected behavior**
The actual video being clicked playing.

**Desktop (please complete the following information):**
Windows 10 1909
Jellyfin Shim 1.5.6

**Comment by iwalton3** [comment]
The fix is now released: https://github.com/iwalton3/jellyfin-mpv-shim/releases/tag/v1.5.8

**Comment by Cupbox** [comment]
Thank you.
