### ISSUE TITLE
MPRIS Plugin

### ISSUE THREAD

**Issue by fabianski7** [iwalton3/jellyfin-mpv-shim#54]
**Describe the bug**
I'm trying to load the [mpris plugin](https://github.com/hoyon/mpv-mpris) for the mpv but it's not working.
Adding this same option in `~/.config/mpv/mpv.conf loads` the plugin without problems when mpv runs to other media on my pc.

**To Reproduce**
I added `script=/home/me/.config/mpv/scripts/mpris.so` in `~/.config/jellyfin-mpv-shim/mpv.conf` but when starting `jellyfin-mpv-pris` the console shows the following errors:

```
2020-04-17 14:48:44,959 [   ERROR] mpv: cplayer: C plugin error: '/home/fabiano/.config/mpv/scripts/mpris.so: undefined symbol: mpv_get_property'
2020-04-17 14:48:44,959 [   ERROR] mpv: mpris: Could not load SO plugin /home/fabiano/.config/mpv/scripts/mpris.so
```

Full log https://bin.privacytools.io/?0cd9a8ce68490294#otzSobnT2wxFqGo16Wwk2Q71HrbrI9itjkEXS+/iSK8=

**Desktop (please complete the following information):**
 - OS: archlinux 5.6.4-arch1-1
-  Package: [AUR](https://aur.archlinux.org/packages/jellyfin-mpv-shim/)
 - Version: 1.5.8-1

**Comment by iwalton3** [comment]
Try building mpv from source. I've seen the error where `mpv_get_property` is undefined on older mpv versions. If it works with your command-line `mpv`, you could also try setting `mpv_ext` to `true` in the config file.

I cannot guarantee that Mpris will work well though. The software doesn't queue files into MPV, it instead uses event handlers and keybinds. You'll be able to pause/play, but skipping between files may not work.

**Comment by fabianski7** [comment]
> Try building mpv from source. I've seen the error where `mpv_get_property` is undefined on older mpv versions. 

I'm using the latest version available in the mpv github repository, v0.32.0. 

> I cannot guarantee that Mpris will work well though. The software doesn't queue files into MPV, it instead uses event handlers and keybinds. You'll be able to pause/play, but skipping between files may not work.

Pause/play should be enough. Other functions would be welcome but those two are already useful.

> If it works with your command-line mpv, you could also try setting mpv_ext to true in the config file.

I commented on the line in `~/.config/jellyfin-mpv-shim/mpv.conf` and modified the `~/.config/jellyfin-mpv-shim/conf.json` like this

```
    "mpv_ext": true,
    "mpv_ext_ipc": null,
    "mpv_ext_path":"/usr/bin/mpv --script=/home/me/.config/mpv/scripts/mpris.so",
    "mpv_ext_start": true,
```

Well, that doesn't work either.[ Here's the error log](https://bin.privacytools.io/?fc99e8c54f4e179d#sFMfy4ZpoVwlaSjSWwjub5nio1VWlm4kyWhV295bFh0=).

```
FileNotFoundError is reported: 
[Error 2] No such file or directory: '/usr/bin/mpv --script=/home/fabiano/.config/mpv/scripts/mpris.so'
```

the path exists. I tested it manually.

**Comment by iwalton3** [comment]
Just set `mpv_ext_path` to null. (Or a path to a binary only.) Put `script=/home/me/.config/mpv/scripts/mpris.so` into `mpv.conf` instead.

**Comment by fabianski7** [comment]
That worked. Thank you.

Using this method will the mpv always stay open in the background? The media icon in the system tray is always being displayed even if nothing is being played back.

**Comment by iwalton3** [comment]
Yes mpv will always be running, even when media is not being played. This is how it works regardless of which mode is in use. (The difference is that with ext mode `mpv` runs as a separate process controlled via a socket instead of hosted as a shared library from the python process.)

**Comment by fabianski7** [comment]
Ok. 
Maybe this (mpris plugin support) could be added to Readme. 
If necessary, you can close this issue. Thank you so much for the quick support.

**Comment by iwalton3** [comment]
I have added a "Tips and Tricks" section to the README with this and a few other issues documented.
