### ISSUE TITLE
can't connect to server

### ISSUE THREAD

**Issue by moreje** [iwalton3/jellyfin-mpv-shim#58]
**Describe the bug**
just did a fresh install (flatpack) on ubuntu. I can't connect to my server
tried:
192.168.0.50
http://192.168.0.50
http://192.168.0.50:8096
nothing works: unreachable
access from browser is OK

**Expected behavior**
connection to server

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by iwalton3** [comment]
Please launch the program from the terminal with `flatpak run com.github.iwalton3.jellyfin-mpv-shim` and post the output. Make sure to remove any API keys from the log if your server is publicly reachable.

**Comment by moreje** [comment]
thank you for helping me !
here is the output:
`2020-04-21 23:34:18,395 [    INFO] conf: Loaded settings from json: /home/jerome/.var/app/com.github.iwalton3.jellyfin-mpv-shim/config/jellyfin-mpv-shim/conf.json
2020-04-21 23:34:18,515 [    INFO] player: Using libmpv1 playback backend.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/app/lib/python3.7/site-packages/jellyfin_mpv_shim/webclient_view/__init__.py", line 105, in run
    self.srv = make_server('127.0.0.1', 18096, app, threaded=True)
  File "/app/lib/python3.7/site-packages/werkzeug/serving.py", line 848, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/app/lib/python3.7/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

Gtk-Message: 23:34:18.608: Failed to load module "appmenu-gtk-module"
Gtk-Message: 23:34:18.791: Failed to load module "appmenu-gtk-module"
`

**Comment by iwalton3** [comment]
It looks like you have another copy running already. Quit all copies and run it in the terminal again. Then send the output.

**Comment by moreje** [comment]
oups, sorry! edited!

**Comment by iwalton3** [comment]
I don't see anything unusual in there. If you try logging in, do you get any additional messages in the logs in the terminal or any specific error message on the screen?

The systray icon is only used with the "Shim" version. The "Desktop" version doesn't use the icon. If you are using the shim version, you can get the log messages by passing `--shim` when you launch it in the terminal.

**Comment by moreje** [comment]
if I try logging in I get the following message in app (in french)
Connection failed. We are in the impossibility to connect to specified server. please check if it is operational and try again
nothing in the console while trying

**Comment by iwalton3** [comment]
Do you have a baseurl set? When you visit `http://192.168.0.50:8096` in a browser, what URL are you redirected to? You can also try logging in with it running in shim mode (`flatpak run com.github.iwalton3.jellyfin-mpv-shim --shim`) which may produce a more helpful error message.

**Comment by moreje** [comment]
yesss! thank you so much!
I had to add the baseurl:
192.168.0.50:8096/jellyfin
now I reqch my server! 
I can test your software!!
