### ISSUE TITLE
[Feature Request] keyboard play/skip (fn) keys

### ISSUE THREAD

**Issue by ethanponchi2000** [iwalton3/jellyfin-mpv-shim#59]
Heyo, small request - would be lovely to have the play/skip/stop buttons on they keyboard (fn keys) to work with the client.

Thanks for the hard work!

**Comment by iwalton3** [comment]
Last I checked, media keys were working. What platform are you running the software on and how did you install it?

**Comment by ethanponchi2000** [comment]
Hey thanks for the prompt reply - I was a bit unclear there sorry; the media keys are working when the software is selected/active, though when I click onto a browser or something else they don't seem to work. I'm running the windows version, set up through the installer (1.5.5) with jellyfin 10.5.3

**Comment by iwalton3** [comment]
It looks like you might need to use something like AutoHotKey to do that. MPV doesn't support global hotkeys.

**Comment by ethanponchi2000** [comment]
Cool, Autohotkey sounds like a plan - thanks!

**Comment by topas-rec** [comment]
I tried version 1.8.0 from flathub and the media keys that for example Rhythmbox reacts to (Play, pause, skip) didn't work when Jellyfin MPV Shim was plaing a song and was in focus. I thought this would work and I think that should work.

**Comment by iwalton3** [comment]
@topas-rec Please open a new issue for this. This issue was related to global media keys on Windows.

If you can, would you be able to try using the media keys with the PyPI version? Flatpak has been known to break things, so I want to know if it is Flatpak or your desktop environment that is causing media keys to not work.

**Comment by topas-rec** [comment]
@iwalton3 I cannot finish install from pypi and created a bug for that first: https://github.com/iwalton3/jellyfin-mpv-shim/issues/136
