### ISSUE TITLE
Unable to choose what file (4K or 1080) to play

### ISSUE THREAD

**Issue by harry71019** [iwalton3/jellyfin-mpv-shim#6]
There are several files in my library that I have 2 files (4K HDR and 1080p), you can choose which one to play from from the jellyfin web client like this.
![image](https://user-images.githubusercontent.com/59645782/72593160-492a0680-38d2-11ea-8363-7185255b9327.png)
However, even if I choose the 1080p one it still plays the 4K one in mpv.
![image](https://user-images.githubusercontent.com/59645782/72593204-65c63e80-38d2-11ea-996d-0b662f55e861.png)

Here's what the console show when trying to play the two different resolution files.
[play1stFile.txt](https://github.com/iwalton3/jellyfin-mpv-shim/files/4075563/play1stFile.txt)
[play2ndFile.txt](https://github.com/iwalton3/jellyfin-mpv-shim/files/4075564/play2ndFile.txt)

**Comment by iwalton3** [comment]
I'm not currently handling the MediaSourceId parameter that determines what version is played. It should be straightforward for me to fix it.

**Comment by iwalton3** [comment]
Solved by latest release.
