### ISSUE TITLE
Unable to reset pan-scan settting using normal MPV hotkeys

### ISSUE THREAD

**Issue by meebsmagee** [iwalton3/jellyfin-mpv-shim#62]
**Describe the bug**
I accidentally hit the "e" key on my keyboard, which adjusts the pan-scan setting. Now every time I open a media file the playback is zoomed in while in fullscreen mode. I checked with MPV for the hotkey to reset panscan (or change the value lower), but unfortunately it is bound to "w" - and MPV shim overrides this hotkey. I seem to be unable to find a way to reset it to default.

**To Reproduce**
1. Open a media file with MPV shim
2. Press "e" repeatedly until the panscan value is maxed out.
3. Make sure the video is fullscreen and observe that it is now zoomed in.

**Expected behavior**
I would expect to be able to press "w" in order to set the panscan back to 0. Perhaps the increase panscan hotkey "e" should be disabled while using MPV shim? Or the hotkeys could be moved to another set of keys.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. 1.2.0]

Maybe I'm overlooking something, any help would be much appreciated. Thank you!

**Comment by iwalton3** [comment]
You can restart the application to clear the setting. The input.conf allows you to remap keyboard shortcuts that aren’t custom. (Currently remaking custom shortcuts is not implemented.)

**Comment by iwalton3** [comment]
I will be looking into a configuration mechanism that allows for customizing keyboard bindings. How exactly this will work remains to be seen though. (See also: https://github.com/iwalton3/plex-mpv-shim/pull/15)

**Comment by meebsmagee** [comment]
I was able to reset the pan-scan and have now unbound the "e" key using input.conf in order to avoid doing this again. I'll close this ticket now, thank you for all your work on this amazing project!

Also, I am glad to hear about the "stop overwriting 'esc' behavior" merge. I'm going to be installing this on my mom's media center and she is used to using ESC to exit fullscreen. Thanks again!

**Comment by iwalton3** [comment]
It may be a bit until I have a release with the `esc` functionality merged. The current way to exit fullscreen is to press `f`. You can stop and close the player by pressing `q` or by canceling playback from a casting device (if applicable).
