### ISSUE TITLE
mpv does not start

### ISSUE THREAD

**Issue by johnbrz** [iwalton3/jellyfin-mpv-shim#63]
**Describe the bug**
When I select jellyfin-mpv-shim as the jellyfin player and select a video, nothing happens. The mpv is not started and I also can't change the player to another one, I have to close the browser tab and open it again.

**Logs**
[Console](https://bin.snopyta.org/?9e168b9c903f598b#D8ow5Ahr4eTEa43U9mH6h5iEf2LaiHCV5vn6j74V8rYK)
[CLI](https://bin.snopyta.org/?b8e1a973cad86959#9EtQQgoYWthNMzt9jThDsAAQvLfGMQW2mDPD6vsLiVY9)

**Desktop (please complete the following information):**
Operating System: Arch Linux 
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.6.13-arch1-1
OS Type: 64-bit

**Comment by iwalton3** [comment]
Looks like a “null” start index is being passed from the playback event instead of 0 or omitting the property.

Please test the master branch, which should have a fix. Let me know if it is fixed so I can release a hotfix version.

**Comment by johnbrz** [comment]
Thanks for the fix. The mpv is starting correctly now.

What still does not work is the option to select the player. Once I have selected mpv-shim, it is not possible to use the web player again ([video](https://upload.disroot.org/r/BqaVVc2K#eCafKLyW7tsa6T3oQXeVV6jDmEhUrBI5nuTRfUBYcjc=)). 

Maybe this is a bug of the jellyfin web client?
[
Browser console log](https://bin.privacytools.io/?ec6ec66d72371e8e#zmOJCtn1FCrbzRiJtpM/PAKU8IHn25lRC0qdxiKFoS4=)
[jellyfin-mpv-log](https://bin.privacytools.io/?79990c0f8f002174#zl8RWmNRU04JYIwpZPzCMA/RAfGBOjlSMpLzHdTBPhY=)

**Comment by iwalton3** [comment]
Looks like a bug with the web client: https://github.com/jellyfin/jellyfin-web/blob/b3d0394fd109b159c26e8f253678a2cfd74172c9/src/components/playback/playerSelectionMenu.js#L227

The playerInfo.supportedCommands appears to be null, but my player should be sending that. Are you running nightly? That would also explain the unusual API calls that have StartIndex as null when it was always not present in my testing.

**Comment by fabianski7** [comment]
Okay. Thanks.

And yes, I'm using the nightly version (git).

**Comment by johnbrz** [comment]
yes I'm using the nightly (git) version. Thanks.
