### ISSUE TITLE
Playback breaks if you rename the computer

### ISSUE THREAD

**Issue by krizly** [iwalton3/jellyfin-mpv-shim#64]
**Describe the bug**
If you rename your computer with MPV Shim Desktop installed the application does not update the connection with the MPV Shim application (you can see the old PC name in the top right corner next to the cast button).

**To Reproduce**
1. Install MPV Shim desktop application
2. Connect to your Jellyfin server
3. Rename your computer
4. Open MPV Shim Desktop and attempt to play content

**Desktop (please complete the following information):**
 - OS: Windows 10
 - MPV Shim Desktop version - 1.5.9

**Error Messages**
No error messages show, when attempting to play content nothing happens.
Current workaround is to rename/delete the %appdata% MPV Shim folder and re-connect the application to the Jellyfin server.

**Comment by iwalton3** [comment]
You have to update the connection name in the config file after first run. (The computer name is used as the default.)

Please see: https://github.com/iwalton3/jellyfin-mpv-shim#other-configuration-options

**Comment by iwalton3** [comment]
Please use the debug version here: https://iwalton.com/ushare/jellyfin-mpv-desktop_1.5.9_debug.exe

Post the log messages related to the issue. Please be sure to remove any API keys if your server is publicly reachable.

**Comment by ddevler** [comment]
I have a very similar issue. It might be the actual cause of the above error.  It took me a bit to figure out the actual cause. Win10 installed updates overnight then auto rebooted the machine.  After the reboot the app stops working until you delete the AppData jellyfin-mpv-shim and reconfigure the app. Basically his issue above happens. No error message but the GUI isn't drawn.

Steps to repeat:
1) open Jellyfin Desktop app configured with server.
2) reboot with app still open
3) launch app. No interface will appear or error message. Only way get it working again is to delete the Jellfin-mpv-shim in AppData Roaming and then reconfigure server.

**Comment by iwalton3** [comment]
Update: I tried reproducing this. No luck after rebooting the VM with the player open 3 times. Do you happen to have the setting enabled in Windows that re-opens applications from your last session?

**Comment by ddevler** [comment]
I've been back on linux side for while so haven't while used the windows version recently. My guess is it was related to the issue of desktop positioning. I think the browser display was launching off screen. PC has dual monitor and it didn't appear on either of them.

**Comment by iwalton3** [comment]
Ok. I'm going to close this. If anyone has this type of issue with the latest version, please re-open this and provide as much information as possible, [particularly logs](https://github.com/iwalton3/jellyfin-mpv-shim/wiki/Sending-Logs).
