### ISSUE TITLE
SyncPlay support?

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [iwalton3/jellyfin-mpv-shim#65]
Does this support the upcoming SyncPlay feature, or will it require implementing a new API endpoint? (Not sure how it controls playback, if Jellyfin already has an API for this (that MPV Shim would already support, being a Jellyfin client), or if it was implemented just for SyncPlay)

**Comment by iwalton3** [comment]
I haven't investigated it yet. I was planning on waiting for the PR to be finalized and merged to implement support if additional work is needed.

**Comment by ThatNerdyPikachu** [comment]
Gotcha. As far as I can tell, I doubt there will be any underlying implementation changes, maybe just some code cleanup, so I'd say it's fair game to start looking at in now.

I'll take a look whenever I can.

**Comment by mcarlton00** [comment]
I don't mean to discourage, but maybe hold on spending any significant time implementing this until after 10.6 releases.  I started looking into adding support for Kodi and found several things about the API that we didn't like and are changing before release.  Just throwing that out there before anybody invests a bunch of time into it.

**Comment by iwalton3** [comment]
@mcarlton00 Any update on API stability and changes? Is the API (relatively) stable now that 10.6 is released?

**Comment by mcarlton00** [comment]
It _should_ be.  The brunt of the API endpoints are going to be found [here](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Api/SyncPlay/SyncPlayService.cs) (not written up nicely anywhere yet.  That's on my todo list once I figure out how to get it into Kodi).

Note that there's currently a limitation that you can only create a group once media is already playing.  There's an open PR adding this, but it didn't make it into 10.6.0.

**Comment by whalehub** [comment]
@iwalton3 This would be a killer feature to have because this is currently the only desktop client on Windows that can Direct Play HEVC media files. 👍

**Comment by iwalton3** [comment]
This was implemented in 1.7.0.
