### ISSUE TITLE
 Change of language to Spanish

### ISSUE THREAD

**Issue by angeltonio** [iwalton3/jellyfin-mpv-shim#68]
I have my jellyfin on Spanish language, but when i open Jellyfin-mpv-shim, the menus and things are on English??..why this happens??...It´s about the compilation of the program??..cheers

**Comment by iwalton3** [comment]
At this time the program's internal menus are all English-only. The desktop client embeds the Jellyfin web app, so that part of the program should be localized, but any of the mpv-shim specific menus aren't translated and there is currently no localization system implemented.

**Comment by iwalton3** [comment]
I should probably look into making localization possible, but I would need to get other people to translate the UI. Currently I know I have people using the application that speak Chinese, Spanish, and French.

**Comment by angeltonio** [comment]
I can help you but with the spanish, because it´s my mother tongue...cheers

**Comment by iwalton3** [comment]
I have added initial localization support. I will probably try to get set up with something like Weblate to make translation easier.

This is the language template file: https://github.com/iwalton3/jellyfin-mpv-shim/blob/master/jellyfin_mpv_shim/messages/base.pot

**Comment by iwalton3** [comment]
@angeltonio You can now translate the application on Jellyfin's Weblate instance!
https://translate.jellyfin.org/projects/jellyfin/jellyfin-mpv-shim/

**Comment by angeltonio** [comment]
> @angeltonio You can now translate the application on Jellyfin's Weblate instance!
> https://translate.jellyfin.org/projects/jellyfin/jellyfin-mpv-shim/

I put you a fork with the transtalation do you see it??..cheers

**Comment by iwalton3** [comment]
I don't see a translated file in the forked version.

If you have a translated language file, you should be able to go here: https://translate.jellyfin.org/projects/jellyfin/jellyfin-mpv-shim/es/
Create an account, then click on Files > Upload Translation.

**Comment by iwalton3** [comment]
I've updated my processes so that translations can be updated. I have verified that Weblate is picking up changes as well, which should be via webhook or periodic pulls. (I'm not quite sure.)

Here is a Windows test build: https://iwalton.com/ushare/jellyfin-mpv-desktop_trstest_installer.exe
I would like to confirm that the translations are actually taking effect on the test version properly. Please let me know if there are any problems.

**Comment by iwalton3** [comment]
I have confirmed that language detection works correctly on Windows.
