### ISSUE TITLE
Support for SyncPlay

### ISSUE THREAD

**Issue by KGT1** [iwalton3/jellyfin-mpv-shim#71]
With SyncPlay now in nighly, i would like to ask if you will support it.
Because i dont think it will be as easy as to update the webui(maybe it is idk), will you add support for it at some point in the future, with the 10.6.0 release or even earlier?

Love the Player btw, great work!

**Comment by iwalton3** [comment]
This is on my roadmap. I’ve got a lot of stuff to do on this project and less time to do it, so it may be a few weeks bit before it is implemented.

**Comment by iwalton3** [comment]
Tracked in https://github.com/iwalton3/jellyfin-mpv-shim/issues/65
