### ISSUE TITLE
Connection Failure with HTTPS url on Desktop version

### ISSUE THREAD

**Issue by Ashyni** [iwalton3/jellyfin-mpv-shim#77]
**Describe the bug**
Hello, Jellyfin MPV shim version works fine with http (local/ip) or https (ext/domain) url but Desktop only works with http.
Using https on Desktop and we get stuck with Connection Failure.
The browser still see the MPV player even with the connection failure, and it's fully working.
The authentication is good server side, websocket works too.
I've use the 1.5.9 debug version find in another issue to get log.

http is direct
https is behind Traefik + Cloudflare Proxy

**To Reproduce**
1. Try to connect with an https url with the Desktop version
2. Connection Failure
3. Back to step 1

**Expected behavior**
Having a successful authentication.

**Screenshots**
![JMPVD](https://user-images.githubusercontent.com/18462848/84540474-b745ee80-acf5-11ea-865c-a6a0f449a43a.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [1.5.10/1.5.9]
 - Jellyfin [10.5.5]

**Error Messages**
https://pastebin.com/vXuijkZH

**Comment by iwalton3** [comment]
If you connect to the webapp server (http://127.0.0.1:18096/index.html) while the desktop app is running, are you able to connect to your server? If not, are there any errors in the F12 console on the browser? Does your proxy have `Access-Control-Allow-Origin: *` in the headers?

**Comment by Ashyni** [comment]
Hello, thanks for your help, it was indeed a CORS issue on my end, middleware CORS headers added by Traefik conflicting with the one already in jellyfin, once removed, all good.
Sorry for wasting your time, i apologize.
