### ISSUE TITLE
Use local mpv configuration when running external mpv

### ISSUE THREAD

**Issue by dufferzafar** [iwalton3/jellyfin-mpv-shim#78]
**Is your feature request related to a problem? Please describe.**
I have my own mpv configuration - stored in `~/.config/mpv/mpv.conf` - but when I launch mpv from jellyfin it ignores my config. So for eg in my config, `s` key is used to toggle subtitles, which gets overridden by screenshot.

**Describe the solution you'd like**
When `mpv_ext` is `True` and a user config exists for mpv, it should be preferred over mpv-shim's config.

**Comment by iwalton3** [comment]
MPV Shim uses it's own [input configuration](https://github.com/iwalton3/jellyfin-mpv-shim#mpv-configuration) to avoid conflicts with user configuration files. You are free to edit the configuration, but I do not want to use the default one because it will result in unexpected behavior for users. (For instance, users with `keep-open` enabled with their regular MPV config will render MPV Shim unusable.)

**Comment by iwalton3** [comment]
Please let me know if there is a use case isn't supported by the current configuration scheme. You should be able to do anything with the two config files I expose in the settings folder (`mpv.conf` and `input.conf`).

You may also be interested in exploring the configuration profiles, which allow you to add shaders and mpv options and easily change between them at runtime, including from the mobile app through the menu. (See the details [here](https://github.com/iwalton3/jellyfin-mpv-shim#shader-packs-1) and an example configuration you can customize [here](https://github.com/iwalton3/default-shader-pack/blob/master/pack.json).)

If there is some configuration that is not enabled by the configuration options I have created, re-open the issue and let me know. It is my goal that this software is very configurable. I may need to add some features or enable an override that uses the builtin config (with the caveat that this is disabled by default, to prevent unintended breakage). I would prefer to just use the separate configuration unless there is a good reason to add this though.

**Comment by iwalton3** [comment]
This has been implemented as an optional setting due to additional requests.
