### ISSUE TITLE
Set sane default value for remote streaming bandwidth

### ISSUE THREAD

**Issue by whalehub** [iwalton3/jellyfin-mpv-shim#8]
**Is your feature request related to a problem? Please describe.**
The default remote streaming bandwidth is currently set to 2000kbps. I don't think that this is a sane default value for a desktop application because it prevents users from Direct Playing most 1080p and 4K content. I'm not even sure what its intended purpose is since residential Internet, unlike mobile Internet, is not subject to data caps. On my Jellyfin server, the current default value only serves to cause my users to transcode media unnecessarily.

**Describe the solution you'd like**
I think that the default value should be set high enough so that non-technical users can Direct Play 1080p and 4K content without first having to modify obscure config files.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by iwalton3** [comment]
I used 2mbps because that is the default that Plex uses on their clients. Do you think 10 mbps is a more reasonable value? That is half the typical residential upload speed and also the typical bandwidth of a 1080p h264 stream.

**Comment by anthonylavado** [comment]
> I'm not even sure what its intended purpose is since residential Internet, unlike mobile Internet, is not subject to data caps.

Just an aside - remember that internet connectivity and policies vary wildly around the world. For example, I don’t have a residential data cap, but someone else might. There are even Jellyfin team members in the United States who have data caps.

That said, a higher value seems like a good idea.

**Comment by iwalton3** [comment]
The bandwidth limit can be set lower by the server admin. I think 10 mbps is a reasonable option considering it should work for most connections by default.

Also this value is configurable via the built-in menu, which is accessible via `c` within the player, Tray Icon > Application Menu, or Mobile App Home/OK (when support is added).
![image](https://user-images.githubusercontent.com/8078788/72810382-70166e80-3c2b-11ea-884d-deea2dac5887.png)

**Comment by iwalton3** [comment]
This has been reconfigured to 10 Mbps for new users in version 1.3.0. I have also included instructions on how to change it in the release for existing users.
