### ISSUE TITLE
Scrubbing at beginning of file skips to next episode

### ISSUE THREAD

**Issue by Jerrk** [iwalton3/jellyfin-mpv-shim#83]
Using Jellyfin MPV Desktop

**Describe the bug**
When just finishing an episode of a season and moving on the the next episode, while the new episode is buffering if you scrub forward it will often skip forward a couple episodes. 
This is a really annoying issue when watching non-linear content because i've accidentally skipped several episodes since the story doesn't follow episode by episode.

**To Reproduce**
1. Go to a season of any series
2. Start playing a series
3. Move close to end of current episode
4. Start scrubbing forward (with your mouse wheel)
5. Episodes are skipped (this doesnt happen 100% of the time but it is very frequent)

**Expected behavior**
The episode should scrub without skipping to the next episode.

**Screenshots**
heres a quick video of the issue happening, i'm only scrubbing with my mouse scrollwheel.
https://streamable.com/wz11xg

and heres my input.conf edit regarding my scrollwheel
```
# Wheel #
WHEEL_UP seek 1
WHEEL_DOWN seek -1
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.5.10

**Error Messages**

Edited the log to only show the time around the playing of the series

[logs.txt](https://github.com/iwalton3/jellyfin-mpv-shim/files/4844686/logs.txt)

**Comment by iwalton3** [comment]
This is a known issue. The system uses an event queue, which gets overwhelmed when the scroll wheel is used towards the end of the episode, causing the finished event to fire several times.

**Comment by iwalton3** [comment]
This will be fixed in the next release.

**Comment by iwalton3** [comment]
This is now in 1.5.11.
