### ISSUE TITLE
Using External Shaders?

### ISSUE THREAD

**Issue by aaronson2012** [iwalton3/jellyfin-mpv-shim#85]
Is it possible to use external shaders (Specifically Anime4K) with jellyfin-mpv-shim.

I've tried 2 things:
First I tried using my already set up mpv instance, and that resulted in mpv displaying a blue screen.
Then I tried copying over my shaders folder and editing mpv.conf in %appdata%\jellyfin-mpv-shim. And the shaders just outright didnt run there.

Any ideas?

**Comment by iwalton3** [comment]
I use Anime4K with this software. Please make sure that:

 - You have not pasted the shaders into a file with any blank lines between comments.
 - Specify the full path to the shaders, don’t use `~~`.
 - Make sure you are using the correct path separator in mpv.conf for your platform.

**Comment by aaronson2012** [comment]
> 
> 
> I use Anime4K with this software. Please make sure that:
> 
>     * You have not pasted the shaders into a file with any blank lines between comments.
> 
>     * Specify the full path to the shaders, don’t use `~~`.
> 
>     * Make sure you are using the correct path separator in mpv.conf for your platform.

Thanks for the tips. After getting the shaders to load in the built in mpv im left with the blue screen again. Any ideas what might be causing that? I searched through the log but didnt find anything.
[log.txt](https://github.com/iwalton3/jellyfin-mpv-shim/files/4918693/log.txt)

**Comment by aaronson2012** [comment]
Actually I got it working. Changing the video api from opengl to vulkan fixed it. Thanks!
