### ISSUE TITLE
Issues with direct play

### ISSUE THREAD

**Issue by aaronson2012** [iwalton3/jellyfin-mpv-shim#86]
I cant seem to get this to direct play my 4k content. Is there an option to force direct play every time? I tried setting the max bitrate in the conf file to above the bitrate of my 4k content and that didn't seem to work.

**Comment by aaronson2012** [comment]
I managed to get it to always direct play by disabling transcoding on my user, but thats not ideal. Anyone have any ideas?

**Comment by iwalton3** [comment]
Please post logs with "log_decisions" set to true. (You can leave "mpv_log_level" at the default.)

**Comment by aaronson2012** [comment]
> 
> 
> Please post logs with "log_decisions" set to true. (You can leave "mpv_log_level" at the default.)

Hey, are you referring to the mpv log? If so here you are: [log.txt](https://github.com/iwalton3/jellyfin-mpv-shim/files/4921524/log.txt) or is it another log? I did a quick search in the log for "decisions" but couldn't find any relevant info. Also, I'm using an external mpv instance. does that matter? Thanks!

**Comment by iwalton3** [comment]
You can change the log_decisions setting in the conf.json file. (There are details about this file in the readme.) If you run the program in "Shim" mode there is a status icon that lets you see log messages ("Show Console"), then cast the 4K media to the player. That will display the media decision from the Jellyfin server that is causing the transcode.

If you are using a server that is not on your local network, make sure to change the bitrate configured for remote sources.

**Comment by aaronson2012** [comment]
Thanks! I got the correct log this time.
[shim.log](https://github.com/iwalton3/jellyfin-mpv-shim/files/4921619/shim.log)

**Comment by aaronson2012** [comment]
Okay, I figured it out. I had to change the remote bitrate setting as you said. Thanks!
