### ISSUE TITLE
libmpv.so.1 attribute error

### ISSUE THREAD

**Issue by bipox** [iwalton3/jellyfin-mpv-shim#88]
Hi!

When installed with pip, jellyfin-mpv-shim (or desktop) won't start.

```
jellyfin-mpv-shim 
2020-07-21 12:36:35,981 [    INFO] conf: Loaded settings from json: /home/remi/.config/jellyfin-mpv-shim/conf.json
Traceback (most recent call last):
  File "/usr/local/bin/jellyfin-mpv-shim", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jellyfin_mpv_shim/mpv_shim.py", line 54, in main
    from .player import playerManager
  File "/usr/local/lib/python3.6/dist-packages/jellyfin_mpv_shim/player.py", line 23, in <module>
    import mpv
  File "/usr/local/lib/python3.6/dist-packages/mpv.py", line 567, in <module>
    _handle_func('mpv_render_context_create',               [MpvRenderCtxHandle, MpvHandle, POINTER(MpvRenderParam)],   c_int, ec_errcheck,     ctx=None)
  File "/usr/local/lib/python3.6/dist-packages/mpv.py", line 478, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libmpv.so.1: undefined symbol: mpv_render_context_create
```
I have MPV and libpmv installed.

**Desktop (please complete the following information):**
 - OS: Linux, KDE Neon
 - Version: latest

I had it installed this way for a while and it worked, then I switched to the flatpak version. Flatpak version doesn't work correclty (I'll post later), so I tried to go back to python, and this issue appeared.

**Comment by iwalton3** [comment]
The “undefined symbol: mpv_render_context_create” means the copy of python-mpv you have is not compatible with the version of libmpv1 you installed.

You can try:

 - Install an `mpv` binary and set `mpv_ext` to true in the config.
 - Upgrade python-mpv: `sudo pip3 install —upgrade python-mpv`
 - Build MPV from source.

For flatpak try running a `flatpak update --system`. None of the above items will help with flatpak.

**Comment by bipox** [comment]
Thanks

I tried with mpv_ext set to true but it didn't work (I tried entering the path and leaving "null")
`python_mpv_jsonipc.MPVError: error accessing property`

Flatpak version is up to date, but the desktop interface is very slow, and I can't open a tv show. When I click on a show, instead of opening it hangs then selects all shows (with the shows highlighted and the little "select" square)

**Comment by iwalton3** [comment]
> python_mpv_jsonipc.MPVError: error accessing property

Well, that means both of the libraries don't work with your MPV version. Compiling from source is likely the only option.

If you are having performance issues with the desktop interface in Flatpak, it may be helpful to try the "shim" version and connect to it from your web browser. That version has better performance characteristics.

The Flatpak version did work when I tested it, but it is known to have issues on Wayland and with Nvidia drivers (the latter was solved by updating Flatpak).

**Comment by bipox** [comment]
I'll try to update MPV.

As for using only the shim version of flatpak, I haven't figured it out. When I launch shim instead of desktop, it opens the desktop interface anyway.

I'm not using Wayland, and with AMD drivers.

Thanks for taking the time to help!

**Comment by iwalton3** [comment]
Update: It looks like Flatpak broke the shim mode.

> Desktop version is still not working correctly, but I've made an electron version with nativefier.

If you set your desktop version to open `http://127.0.0.1:18096/index.html` and replace [lines 189-207 here](https://github.com/iwalton3/jellyfin-mpv-shim/blob/master/jellyfin_mpv_shim/webclient_view/__init__.py#L189) with `input()`, you can get a better UI experience with that electron version you mentioned.

**Comment by iwalton3** [comment]
I have the shim version fixed with Flatpak. (See https://github.com/iwalton3/jellyfin-mpv-shim/issues/89.) I'm going to mark this as closed, let me know if there are still any remaining issues.
