### ISSUE TITLE
Shim Version broken in Flatpak

### ISSUE THREAD

**Issue by iwalton3** [iwalton3/jellyfin-mpv-shim#89]
**Describe the bug**
It looks like the Flatpak environment is changing underneath the application. `pystray` also updated over the last release cycle, but it still works with the pip version. (Found while verifying application for #88.)

**To Reproduce**
1. Run `flatpak run com.github.iwalton3.jellyfin-mpv-shim --shim`
2. The application will fail to load with an exception.

**Expected behavior**
The application will load and function as expected.

**Desktop (please complete the following information):**
 - OS: Linux, Debian Stable
 - Version: 1.5.11

**Error Messages**
```
Process STrayProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/app/lib/python3.7/site-packages/jellyfin_mpv_shim/gui_mgr.py", line 380, in run
    from pystray import Icon, MenuItem, Menu
  File "/app/lib/python3.7/site-packages/pystray/__init__.py", line 48, in <module>
    Icon = backend().Icon
  File "/app/lib/python3.7/site-packages/pystray/__init__.py", line 40, in backend
    return importlib.import_module(__package__ + '._' + module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/app/lib/python3.7/site-packages/pystray/_appindicator.py", line 22, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

**Comment by mr4ffe** [comment]
I found a strange behavior related to this. If you open the web interface of Jellyfin and cast a video to jellyfin-mpv-shim the program seems to start (though it may just be the pip version, not sure).

**Comment by iwalton3** [comment]
If you disable the GUI in the config it should work based on the error.

**Comment by iwalton3** [comment]
I have gotten Shim mode working in Flatpak again by bundling a copy of libappindicator with the program. It is currently deploying on FlatHub and should be available soon.

**Comment by franzpoeschel** [comment]
I saw a similar issue in the pip-installed distribution, installing `libappindicator3-dev` via apt isolved it. That one pulls many dependencies, so there might be a better package to install, but this might be worth mentioning in the Readme.
