### ISSUE TITLE
HiDPI scaling with jellyfin-mpv-desktop .... text is really small.

### ISSUE THREAD

**Issue by dessalines** [iwalton3/jellyfin-mpv-shim#90]
Overall its a great wrapper, but all the text is really tiny and not scaling. Is there maybe an environment variable or command line switch we could pass to it?

**Comment by iwalton3** [comment]
What operating system has the HiDPI issue? There is no scaling factor right now built in, but you might be able to mitigate the issue for now with compatibility mode if this is on Windows.

**Comment by dessalines** [comment]
Arch linux.

**Comment by iwalton3** [comment]
Try adding the following to the `jellyfin_mpv_shim/webclient_view/webclient/index.html` in the location where pip installed the package:
```html
<style>
body {
    zoom: 2;
}
</style>
```
You can vary the zoom value as desired.

**Comment by iwalton3** [comment]
Did this work? Should I add a config option that automatically injects this into the web client?

**Comment by dessalines** [comment]
It did work, I don't know what kind of web wrapper this is using, but most have a hidpi mode that would avoid the need for that.

**Comment by iwalton3** [comment]
The upstream library doesn’t give me a whole lot of options for this, hence the interest to implement a separate scaling setting. I’ll look into adding that.

**Comment by iwalton3** [comment]
Ok I have added the config option `desktop_scale`, which will allow scaling the web client by any fractional scale.
