### ISSUE TITLE
Player size

### ISSUE THREAD

**Issue by dhaos21** [iwalton3/jellyfin-mpv-shim#91]
Is there any way to have the player a certain size? at the moment you can only pull from the corner (increasing the size horizontally and vertically) is there a way to just increase one way?

**Comment by iwalton3** [comment]
On all platforms I’ve tested on you can resize the display and it will just add black bars if it isn’t the right aspect ratio. What platform are you on?

I guess you could try adding `no-keepaspect=yes` to the `mpv.conf` file. I’m surprised this would be desired though, as it will distort the video.

**Comment by dhaos21** [comment]
When i adjust it on windows you can only adjust it diagonally, you can't for instance make it longer in height without making it longer in length. (the first screen where you pick your media is fine, it's the 2nd screen that actually plays the file)

**Comment by iwalton3** [comment]
Just to note recent testing on Windows and I do have this issue. I will have to investigate further.

**Comment by iwalton3** [comment]
I have confirmed this is MPV default behavior. If you would like to change this, add this to the `mpv.conf` (the location of `mpv.conf` is in the README):
```
no-keepaspect-window
```

I have added this to the "Tips & Tricks" section here: https://github.com/iwalton3/jellyfin-mpv-shim#player-sizing-91
