### ISSUE TITLE
Remember monitor

### ISSUE THREAD

**Issue by gerroon** [iwalton3/jellyfin-mpv-shim#94]
**Is your feature request related to a problem? Please describe.**
The player should remember the last monitor it was playing on.

**Describe the solution you'd like**
Automatic remembering

**Describe alternatives you've considered**
Mpv does not have an option for it?

it would be nice if the player remembers the monitor. I have dual monitor and it seems like the player always want to be on the default monitor, whether "desktop_remember_pos": true or not.

thanks

**Comment by iwalton3** [comment]
Please see: https://github.com/iwalton3/jellyfin-mpv-shim#open-on-specific-monitor-19

MPV doesn't have the same position detection features as the webview library, so currently users have to configure it manually.

**Comment by gerroon** [comment]
Hi

Thanks for the reply. That did not seem to work after a new start :( 

save-position-on-quit
fs=yes
fs-screen=1

**Comment by iwalton3** [comment]
I'm closing this. The documented procedure works, there isn't a good way for me to implement the `fs-screen` setting reliably, so it should be configured through MPV if this is needed using the existing documentation.

If there is ever a case where the documented instructions *do not* work, please open an issue with details for that.
