### ISSUE TITLE
werkzeug returns 404

### ISSUE THREAD

**Issue by JPUnD** [iwalton3/jellyfin-mpv-shim#97]
**Describe the bug**
`jellyfin-mpv-desktop` being run from the terminal on linux shows `werkzeug` returning 404 erros.

**To Reproduce:**
1. Install `jellyfin-mpv-shim` from the AUR with all optional dependencies 
2. Run `jellyfin-mpv-shim` to configure the server, everything works as expected
3. Run `jellyfin-mpv-desktop`

**Expected behavior:**
Jellyfin desktop client should show up, instead `werkzeug` outputs 404 errors on the terminal.

**Desktop:**
- Installed from the AUR `Jellyfin-mpv-shim`
- Distro: Manjaro x86_64
- Kernel: 4.19
- DE/WM: i3-gaps

**Error Messages - Jellyfin Server:**
```
Aug 07 16:55:15 UD-TinyPiNAS jellyfin[12151]: [16:55:14] [INF] [81] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:10.1.1.2 request
Aug 07 16:55:36 UD-TinyPiNAS jellyfin[12151]: [16:55:36] [WRN] [82] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS ::ffff:10.1.1.2 error receiving data: The remote party closed the WebSocket conne>
Aug 07 16:55:36 UD-TinyPiNAS jellyfin[12151]: [16:55:36] [INF] [82] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:10.1.1.2 closed
Aug 07 16:55:41 UD-TinyPiNAS jellyfin[12151]: [16:55:41] [INF] [81] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:10.1.1.2 request
Aug 07 16:55:50 UD-TinyPiNAS jellyfin[12151]: [16:55:50] [INF] [81] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:10.1.1.2 closed
Aug 07 17:01:54 UD-TinyPiNAS jellyfin[12151]: [17:01:54] [INF] [67] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:10.1.1.2 request
Aug 07 17:02:03 UD-TinyPiNAS jellyfin[12151]: [17:02:03] [INF] [68] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:10.1.1.2 closed
Aug 07 17:02:36 UD-TinyPiNAS jellyfin[12151]: [17:02:36] [INF] [74] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:10.1.1.2 request
Aug 07 17:02:55 UD-TinyPiNAS jellyfin[12151]: [17:02:55] [INF] [67] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS ::ffff:10.1.1.2 closed
```

**Error Messages - Desktop Client:**
```
2020-08-07 17:02:36,591 [    INFO] werkzeug: 127.0.0.1 - - [07/Aug/2020 17:02:36] "GET /index.html HTTP/1.1" 404 -
2020-08-07 17:02:36,694 [    INFO] werkzeug: 127.0.0.1 - - [07/Aug/2020 17:02:36] "GET /index.html HTTP/1.1" 404 -
2020-08-07 17:02:36,799 [    INFO] werkzeug: 127.0.0.1 - - [07/Aug/2020 17:02:36] "GET /index.html HTTP/1.1" 404 -
2020-08-07 17:02:36,903 [    INFO] werkzeug: 127.0.0.1 - - [07/Aug/2020 17:02:36] "GET /index.html HTTP/1.1" 404 -
```

**Comment by JPUnD** [comment]
It was worth noting that `jellyfin-mpv-shim` was working as expected and i was able to stream to my device. Both the server and the client are connected through a Wireguard VPN connection with no firewalls between them and Jellyfin has it's webUI currently disabled.

After testing on the same machine but on Windows, since i'm dual booting, after installing and running the client even without the webUI it works as expected, which is what i wanted to since my server is a Raspberry Pi and i'm trying to keep things as light as possible.

This error is weird considering that the client seems to be requesting something to the server, however it still returns a 404.

**Comment by iwalton3** [comment]
I think this is a packaging problem with the AUR. The web client needs to be packaged with the application. Please reach out to the maintainer, I do now maintain the package.

**Comment by JPUnD** [comment]
Damn i was split between sending the issue report here and the AUR, guess I've made a bad decision. 

Thanks for the quick reply i'll post the issue there.

**Comment by bilde2910** [comment]
Thanks for the issue report. I'm the current maintainer for the AUR package, but I have no connection to @iwalton3 and I maintain the package on my own. The issue was a missing dependency, the jellyfin-web fork. This is now added as an optdepend to the package, and should fix the issue. :-)
